// 総合診療 知識アップデート・クイズ 問題バンク
// カテゴリ: journal(新着ジャーナル) / guideline(ガイドライン改訂) / review(定番復習) / clinical(臨床疑問)
// 各問題: added(追加日 YYYY-MM-DD)。correct は数値=単一正解、配列=複数正解(全一致で正解)。
// 問題・解説は日本語、出典は英語リンク。解説は詳細形式(改行\nは表示反映)。
// 医学内容は各出典時点の情報に基づく。実臨床では最新の一次資料を確認すること。

const QUESTIONS = [
  {
    id: "gl-htn-01",
    category: "guideline",
    difficulty: 2,
    added: "2026-07-15",
    question: "2025年 AHA/ACC 高血圧ガイドラインで、心血管リスク評価に用いる推奨ツールとして従来のPooled Cohort Equationsに代わり採用されたのはどれか。",
    options: ["Framingham リスクスコア", "PREVENT リスク計算式", "SCORE2", "QRISK3"],
    correct: 1,
    explanation: "【要点】2025 AHA/ACC高血圧ガイドラインは、心血管リスク推定にPREVENT(Predicting Risk of CVD EVENTs)方程式を採用した。\n【背景】従来のPooled Cohort Equationsは人種を変数に含み、リスクを過大評価する傾向が指摘されていた。PREVENTは人種を除外し、代わりにeGFR(腎機能)や社会的決定要因、必要に応じてUACR・HbA1cも組み込めるため、より現代的で幅広い集団に適合する。\n【臨床応用】30〜79歳で10年および30年リスクを算出でき、130〜139/80〜89 mmHgの層で薬物療法を開始するかの判断に使う。\n【誤答】Framingham/QRISK3/SCORE2はいずれも実在するリスクスコアだが、2025 AHA/ACCが新たに標準採用したのはPREVENTである。",
    source: { title: "Updates in the 2025 AHA/ACC Hypertension Guideline (PMC)", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12995957/" },
    tags: ["高血圧", "リスク評価", "予防"]
  },
  {
    id: "gl-htn-02",
    category: "guideline",
    difficulty: 2,
    added: "2026-07-15",
    question: "2025年 AHA/ACC 高血圧ガイドラインにおける薬物療法開始の考え方について、正しいものはどれか。",
    options: ["収縮期血圧のみで判断し拡張期血圧は考慮しない", "既往CVD・糖尿病・CKD・10年CVDリスク≥7.5%では BP≥130/80 mmHg で薬物療法を推奨", "糖尿病・CKDがあっても確立したCVDがなければ薬物療法は非推奨", "全例で BP≥140/90 mmHg を薬物療法開始基準とする"],
    correct: 1,
    explanation: "【要点】高リスク群では130/80 mmHg以上で薬物療法を推奨する。\n【高リスクの定義】確立したCVD、糖尿病、CKD、または10年CVDリスク≥7.5%。これらでは130/80以上かつ生活習慣是正で不十分なら薬物療法を開始する。\n【重要な変更点】糖尿病・CKDは、確立したCVDがなくても一次予防として薬物療法の対象に含まれる。低リスクの一次予防では、まず3〜6か月の生活習慣介入を試みる。\n【誤答】『140/90を一律基準』は旧来の発想で現行では高すぎる。『糖尿病・CKDでCVD既往がなければ非推奨』は逆。降圧目標は原則<130/80で、収縮期・拡張期の両方を評価する。",
    source: { title: "2025 Hypertension Guideline Updates (AJMC)", url: "https://www.ajmc.com/view/2025-hypertension-guideline-updates-presented-at-aha-scientific-sessions" },
    tags: ["高血圧", "治療閾値", "一次予防"]
  },
  {
    id: "gl-htn-03",
    category: "guideline",
    difficulty: 3,
    added: "2026-07-15",
    question: "2025年 AHA/ACC 高血圧ガイドラインで、原発性アルドステロン症のスクリーニング対象はどのように拡大されたか。",
    options: ["副腎偶発腫を認める症例のみ", "Stage 2 または治療抵抗性高血圧の全例", "低カリウム血症を伴う症例のみ", "スクリーニング推奨は撤回された"],
    correct: 1,
    explanation: "【要点】原発性アルドステロン症(PA)のスクリーニングを、Stage 2または治療抵抗性高血圧の全例に拡大した。\n【なぜ重要か】PAは高血圧の5〜10%程度を占めるが低カリウム血症を伴わないことも多く、大幅に過小診断されている。心血管・腎イベントを本態性高血圧より増やすため、同定できればMRAや副腎摘除で予後改善が狙える。\n【方法】早朝安静時のアルドステロン/レニン比(ARR)でスクリーニングする。\n【誤答】『低K血症例のみ』では正常K血症のPAを大量に見逃す。副腎偶発腫の有無はスクリーニング要否を決めない。スクリーニング推奨は撤回ではなく拡大された。",
    source: { title: "Updates in the 2025 AHA/ACC Hypertension Guideline (PMC)", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12995957/" },
    tags: ["高血圧", "二次性高血圧", "スクリーニング"]
  },
  {
    id: "gl-copd-01",
    category: "guideline",
    difficulty: 2,
    added: "2026-07-15",
    question: "2026年 GOLD COPD アップデートで特に強調された領域として、適切なものはどれか。",
    options: ["早期COPDの検出、多疾患併存(multimorbidity)、AIの活用", "スパイロメトリーの廃止", "在宅酸素療法の適応撤廃", "喫煙者への一律のICS単剤導入"],
    correct: 0,
    explanation: "【要点】2026 GOLDアップデートは、早期COPDの検出、多疾患併存(multimorbidity)、AIの活用を強調した大改訂である。\n【背景】2024年1月〜2025年7月の330本超の新規文献を反映。COPDは心血管疾患・骨粗鬆症・不安/うつ・肺癌などをしばしば合併し、これらが予後を左右するにもかかわらず過小診断・過小治療されている。\n【臨床応用】喫煙歴のある症候例では早期にスパイロメトリーで拾い上げ、併存症を系統的に評価・管理する視点が求められる。\n【誤答】喫煙者への一律ICS単剤導入は不適切(ICSは好酸球や増悪頻度で適応を判断)。スパイロメトリーは診断の要で廃止されておらず、在宅酸素の適応も撤廃されていない。",
    source: { title: "2026 GOLD COPD Update (Pulmonology Advisor)", url: "https://www.pulmonologyadvisor.com/features/gold-copd-update-2026/" },
    tags: ["COPD", "GOLD", "多疾患併存"]
  },
  {
    id: "jr-flow-01",
    category: "journal",
    difficulty: 3,
    added: "2026-07-15",
    question: "FLOW試験(2型糖尿病+CKD、セマグルチド vs プラセボ)で示された主要腎アウトカムの結果として正しいものはどれか。",
    options: ["腎機能悪化をむしろ促進した", "主要腎アウトカムのリスクを約24%低下させた", "腎アウトカムに有意差はなかった", "透析導入を増加させた"],
    correct: 1,
    explanation: "【要点】FLOW試験で、セマグルチド(GLP-1受容体作動薬)は2型糖尿病+CKD患者の主要腎複合アウトカムのリスクを約24%低下させた。\n【試験概要】eGFRやUACRで規定したCKDを持つ2型糖尿病患者を対象に、標準治療へのセマグルチド上乗せをプラセボと比較。腎機能低下・腎不全・腎/心血管死の複合を有意に抑制し、効果はCKD重症度によらず一貫。血糖・体重・血圧の改善も伴った。\n【臨床的意義】SGLT2阻害薬に続き、GLP-1受容体作動薬の腎保護が確立し、糖尿病性腎臓病の主流治療に組み込まれた。\n【誤答】『有意差なし』『腎機能悪化』『透析増加』はいずれも試験結果と逆。",
    source: { title: "Diabetic Kidney Disease — Semaglutide Flows into the Mainstream (NEJM)", url: "https://www.nejm.org/doi/full/10.1056/NEJMe2406408" },
    tags: ["GLP-1", "CKD", "糖尿病", "腎保護"]
  },
  {
    id: "jr-fine-01",
    category: "journal",
    difficulty: 3,
    added: "2026-07-15",
    question: "FINEARTS-HF試験でフィネレノンが対象とした心不全の主な病型と、示された効果はどれか。",
    options: ["急性心筋梗塞後の再梗塞のみを低下", "いずれのアウトカムにも有意な効果を示さなかった", "HFrEF(LVEF<40%)のみで全死亡を低下", "LVEF≥40%の心不全で、心血管死+総心不全イベントの複合アウトカムを低下"],
    correct: 3,
    explanation: "【要点】FINEARTS-HF試験は、主にLVEF≥40%(HFmrEF/HFpEF)の心不全を対象に、非ステロイド型MRAフィネレノンが心血管死+総心不全イベントの複合を有意に低下させることを示した。\n【意義】長らく有効薬の乏しかったHFpEF/HFmrEF領域で、SGLT2阻害薬に続く新たな選択肢。従来のステロイド型MRA(スピロノラクトン等)より高K血症・女性化乳房が少ない設計。\n【注意】導入後は血清カリウムと腎機能のモニタリングが必要。\n【誤答】対象はHFrEFのみではなくLVEF≥40%が中心。急性心筋梗塞後の再梗塞抑制を狙う試験ではなく、複合アウトカムに有意な効果を示した(『効果なし』は誤り)。",
    source: { title: "CVOT summit report 2024 (PMC)", url: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC12048985/" },
    tags: ["心不全", "HFpEF", "MRA", "フィネレノン"]
  },
  {
    id: "jr-vte-01",
    category: "journal",
    difficulty: 3,
    added: "2026-07-15",
    question: "静脈血栓塞栓症(VTE)の延長治療における、減量用量DOAC vs 通常用量DOACを比較した2025年の試験(Lancet)の主眼として最も適切なものはどれか。",
    options: ["ワルファリンへの回帰の妥当性検証", "初期治療でのヘパリン不要化の証明", "延長期における減量用量の有効性・安全性のバランスの検討", "抗血小板薬単独への切り替えの推奨"],
    correct: 2,
    explanation: "【要点】2025年のLancet試験は、VTE延長治療における減量用量DOAC vs 通常用量DOACの有効性・安全性バランスを検討した。\n【文脈】急性期治療(通常3〜6か月)の後も再発リスクが続く症例では延長治療を行うが、長く続けるほど出血リスクが問題になる。アピキサバンやリバーロキサバンには延長期の減量レジメンがあり、再発予防を保ちつつ出血を抑えられるかが臨床課題。\n【実践への影響】総合診療では『抗凝固をいつまで、どの用量で続けるか』の判断に直結する。\n【誤答】初期治療のヘパリン不要化やワルファリン回帰、抗血小板薬単独への切替を主眼とした試験ではない。",
    source: { title: "Update in Outpatient General Internal Medicine 2025 (Am J Med)", url: "https://www.amjmed.com/article/S0002-9343(26)00149-X/abstract?rss=yes" },
    tags: ["VTE", "抗凝固", "DOAC", "延長治療"]
  },
  {
    id: "jr-asa-01",
    category: "journal",
    difficulty: 3,
    added: "2026-07-15",
    question: "経口抗凝固薬を服用中の慢性冠症候群(chronic coronary syndrome)患者において、アスピリンを併用 vs 併用しない場合の考え方として、近年のエビデンス(NEJM 2025)が支持する方向性はどれか。",
    options: ["両者を高用量で併用する", "抗凝固薬を中止しアスピリン単独に切り替える", "全例でアスピリンを上乗せすべき", "多くの安定例では抗凝固薬単独とし、ルーチンのアスピリン併用は避ける方向"],
    correct: 3,
    explanation: "【要点】経口抗凝固薬(OAC)を要する慢性冠症候群(安定CAD)患者では、多くの場合OAC単独とし、ルーチンのアスピリン併用は避ける方向が支持される。\n【根拠】心房細動などでOAC適応があり冠動脈が安定している患者では、アスピリンを上乗せしても虚血イベント抑制の追加効果は限定的な一方、出血(特に消化管・頭蓋内)を有意に増やす。AFIRE試験などと整合し、NEJM 2025のエビデンスもこの方向を補強した。\n【例外】最近のPCI/ACSなど活動性の高い状況では一定期間の併用が必要で、個別判断となる。\n【誤答】全例上乗せ・OAC中止しアスピリン単独・両者高用量併用はいずれも出血リスクの観点から不適切。",
    source: { title: "Aspirin in Patients with Chronic Coronary Syndrome Receiving Oral Anticoagulation (NEJM)", url: "https://www.nejm.org/doi/abs/10.1056/NEJMoa2507532" },
    tags: ["抗血小板薬", "抗凝固", "冠動脈疾患", "出血リスク"]
  },
  {
    id: "rv-asa-01",
    category: "review",
    difficulty: 2,
    added: "2026-07-15",
    question: "高齢者の一次予防目的の低用量アスピリンについて、ASPREE試験が示した結論として正しいものはどれか。",
    options: ["健康な高齢者では全死亡や心血管イベント抑制のnet benefitを示さなかった", "全死亡を有意に低下させた", "認知症発症を予防した", "大出血を減少させた"],
    correct: 0,
    explanation: "【要点】ASPREE試験は、健康な高齢者への一次予防アスピリンが心血管イベント抑制の明確な便益を示さず、大出血を増やすことを示した。\n【試験概要】70歳以上(米国の黒人/ヒスパニックは65歳以上)の心血管疾患・認知症・身体障害のない高齢者を対象に、低用量アスピリンをプラセボと比較。無障害生存に差はなく、大出血が増加。さらに全死亡がやや高い傾向(主に癌関連)も観察された。\n【実践】一次予防でのルーチン投与は非推奨。CVD既往のある二次予防とは明確に区別する。\n【誤答】全死亡低下・認知症予防・大出血減少は、いずれも試験結果と逆である。",
    source: { title: "Effect of Aspirin on All-Cause Mortality in the Healthy Elderly (NEJM/ASPREE)", url: "https://www.nejm.org/doi/full/10.1056/NEJMoa1803955" },
    tags: ["アスピリン", "一次予防", "高齢者"]
  },
  {
    id: "rv-fishoil-01",
    category: "review",
    difficulty: 2,
    added: "2026-07-15",
    question: "魚油(オメガ3脂肪酸)サプリメントの心血管予防効果について、大規模RCT(STRENGTH等)が示した結論に最も近いものはどれか。",
    options: ["全例で心筋梗塞を半減させた", "脳卒中を確実に予防した", "総死亡を大きく低下させた", "心血管保護のベネフィットは示されなかった"],
    correct: 3,
    explanation: "【要点】魚油(オメガ3)サプリメントの心血管保護効果は、大規模RCTで支持されなかった。\n【エビデンス】STRENGTH試験(高用量EPA/DHA)は心血管イベントを減らせず中止された。VITAL試験のオメガ3群も主要複合エンドポイントで有意差なし。処方用の高純度EPA(イコサペント酸エチル)を高TG例に用いたREDUCE-ITは別文脈で陽性だったが、鉱物油対照など解釈上の議論があり、市販サプリとは区別される。\n【実践】心血管予防目的での市販魚油のルーチン推奨は根拠に乏しい。\n【誤答】心筋梗塞半減・脳卒中予防・総死亡低下を示した大規模データはない。",
    source: { title: "Dietary supplements evidence overview (Medscape)", url: "https://www.medscape.com/viewarticle/meaningless-claims-supplement-labels-2025a1000p7o" },
    tags: ["サプリメント", "オメガ3", "予防"]
  },
  {
    id: "cl-aki-01",
    category: "clinical",
    difficulty: 2,
    added: "2026-07-15",
    question: "70歳男性、発熱・脱水で受診。sCr上昇(AKI)を認める。SGLT2阻害薬・ACE阻害薬・NSAIDs・メトホルミンを内服中。急性期にまず一時中止を検討すべき薬剤の組み合わせとして最も適切なのはどれか。",
    options: ["スタチンのみ", "ACE阻害薬・NSAIDs・SGLT2阻害薬・メトホルミン(いわゆるsick day rules)", "薬剤の中止は不要", "PPIのみ"],
    correct: 1,
    explanation: "【要点】急性疾患+脱水+AKIの状況では、いわゆるsick day rulesとして腎血流や代謝に影響しうる薬剤を一時中止する。対象はACE阻害薬/ARB、NSAIDs、SGLT2阻害薬、メトホルミン、利尿薬など。\n【なぜか】ACE阻害薬/ARBとNSAIDsは腎自動調節を障害しAKIを悪化させる。SGLT2阻害薬は脱水下で正常血糖ケトアシドーシスのリスクがあり、メトホルミンはAKIで乳酸アシドーシスの懸念が高まる。\n【運用】あくまで急性期の一時休薬で、回復後に適応を再評価して再開する。患者にシックデイの休薬指導をしておくと有用。\n【誤答】スタチンやPPIのみの中止では不十分で、『中止不要』は危険。",
    source: { title: "Update in Outpatient General Internal Medicine 2025 (Am J Med)", url: "https://www.amjmed.com/article/S0002-9343(26)00149-X/abstract?rss=yes" },
    tags: ["AKI", "sick day rules", "多剤併用", "SGLT2阻害薬"]
  },
  {
    id: "cl-ckd-01",
    category: "clinical",
    difficulty: 3,
    added: "2026-07-15",
    question: "2型糖尿病+CKD(eGFR 45、UACR 300mg/g)の患者。既にSGLT2阻害薬とACE阻害薬を最大耐用量で使用中だが尿蛋白と残余リスクが残る。上乗せとして近年エビデンスが蓄積し推奨される薬剤はどれか。",
    options: ["高用量ビタミンD", "ループ利尿薬の増量", "非ステロイド型MRA(フィネレノン)またはGLP-1受容体作動薬", "NSAIDsの追加"],
    correct: 2,
    explanation: "【要点】SGLT2阻害薬+RAS阻害薬でも残余リスクがある2型糖尿病+CKDでは、非ステロイド型MRA(フィネレノン)またはGLP-1受容体作動薬の上乗せが推奨される。\n【エビデンス】フィネレノンはFIDELIO-DKD/FIGARO-DKDで腎・心血管アウトカムを改善。GLP-1受容体作動薬はFLOWで腎複合アウトカムを約24%低下。これらを組み合わせる『4本柱(RAS阻害薬・SGLT2阻害薬・フィネレノン・GLP-1RA)』の発想が広がっている。\n【注意】フィネレノン導入時は高K血症に留意し、カリウムと腎機能をモニタリングする。\n【誤答】ループ利尿薬増量やNSAIDs追加は蛋白尿・腎保護に寄与せず、NSAIDsはむしろ有害。高用量ビタミンDに腎保護の根拠はない。",
    source: { title: "Finerenone across CKD/CVD spectrum (PMC)", url: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC12539649/" },
    tags: ["CKD", "糖尿病", "フィネレノン", "GLP-1"]
  },
  {
    id: "cl-hf-01",
    category: "clinical",
    difficulty: 2,
    added: "2026-07-15",
    question: "LVEF 55%のHFpEF、2型糖尿病・肥満を合併する労作時呼吸困難の患者。症状・イベント抑制の両面で近年強く支持される薬剤クラスはどれか。",
    options: ["SGLT2阻害薬(および状況に応じGLP-1受容体作動薬・MRA)", "ジゴキシン単独", "特異的治療は存在しない", "長時間作用型硝酸薬単独"],
    correct: 0,
    explanation: "【要点】HFpEF、特に2型糖尿病・肥満を合併する例では、SGLT2阻害薬が中心的で、状況に応じGLP-1受容体作動薬やフィネレノンも選択肢となる。\n【エビデンス】SGLT2阻害薬はEMPEROR-Preserved/DELIVERで心不全入院を抑制(LVEFによらず有益)。肥満合併HFpEFではセマグルチドがSTEP-HFpEFで症状・運動耐容能を改善。LVEF≥40%の心不全ではフィネレノンがFINEARTS-HFでイベントを抑制。\n【実践】かつて『有効薬なし』とされたHFpEFで、治療の柱が確立しつつある。利尿薬はうっ血の対症療法として併用する。\n【誤答】ジゴキシン単独・長時間硝酸薬単独は予後改善の根拠に乏しく、『特異的治療なし』はもはや当てはまらない。",
    source: { title: "CVOT summit report 2024 (PMC)", url: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC12048985/" },
    tags: ["HFpEF", "SGLT2阻害薬", "GLP-1", "肥満"]
  },
  {
    id: "cl-copd-01",
    category: "clinical",
    difficulty: 2,
    added: "2026-07-15",
    question: "COPD増悪を繰り返し、末梢血好酸球数が高値(例:≥300/μL)の患者。GOLDの考え方に沿った吸入療法の調整として適切なのはどれか。",
    options: ["全ての吸入薬を中止", "ICS単剤へ変更", "抗菌薬の連日長期内服を第一選択とする", "LABA/LAMAにICSを追加(トリプル療法を検討)"],
    correct: 3,
    explanation: "【要点】増悪を繰り返し末梢血好酸球が高値(目安≥300/μL)の症例では、LABA/LAMAにICSを追加したトリプル療法を検討する。\n【理由】好酸球数はICS反応性のバイオマーカーで、高値ほどICS上乗せによる増悪抑制効果が期待できる(ETHOS/IMPACT試験)。逆に好酸球が低い(<100/μL)例ではICSの恩恵が乏しく、肺炎リスクを踏まえ減量・中止を検討する。\n【実践】まず気管支拡張薬(LABA/LAMA)を最適化し、増悪頻度と好酸球でICSの要否を判断する。\n【誤答】ICS単剤への変更は気管支拡張が不十分。全吸入中止は不適切。抗菌薬の連日長期内服を第一選択にはしない(一部の頻回増悪例でアジスロマイシン等を考慮する程度)。",
    source: { title: "2026 GOLD COPD Update (Pulmonology Advisor)", url: "https://www.pulmonologyadvisor.com/features/gold-copd-update-2026/" },
    tags: ["COPD", "好酸球", "ICS", "吸入療法"]
  },
  {
    id: "cl-htn-01",
    category: "clinical",
    difficulty: 2,
    added: "2026-07-15",
    question: "45歳、治療抵抗性高血圧(3剤併用でもコントロール不良、うち1剤は利尿薬)。2025 AHA/ACCに沿ってまず考慮すべき評価はどれか。",
    options: ["評価は不要で降圧薬を漫然と増量", "直ちに腎デナベーションを施行", "原発性アルドステロン症のスクリーニング(ARR測定)", "全ての降圧薬を中止して経過観察"],
    correct: 2,
    explanation: "【要点】治療抵抗性高血圧(利尿薬を含む3剤併用でも未達)では、まず原発性アルドステロン症のスクリーニング(ARR測定)を行う。\n【理由】治療抵抗性高血圧ではPAの頻度が高く、2025 AHA/ACCはStage 2/治療抵抗性の全例にスクリーニングを推奨。同定できればMRA(スピロノラクトン等)追加で著明に改善しうる。あわせてアドヒアランス、睡眠時無呼吸、薬剤性(NSAIDs等)、腎動脈狭窄なども評価する。\n【治療】スピロノラクトンが第4剤として有効なことが多い(PATHWAY-2)。腎デナベーションは選択された抵抗例の補助的選択肢。\n【誤答】いきなり腎デナベーション施行、全降圧薬中止、評価なしの漫然増量はいずれも不適切。",
    source: { title: "Updates in the 2025 AHA/ACC Hypertension Guideline (PMC)", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12995957/" },
    tags: ["高血圧", "治療抵抗性", "原発性アルドステロン症"]
  },
  {
    id: "rv-cap-01",
    category: "review",
    difficulty: 1,
    added: "2026-07-15",
    question: "市中肺炎の外来治療における重症度評価で、簡便で救急・外来向きの指標として広く用いられるのはどれか。",
    options: ["GRACEスコア", "Wellsスコア", "CRB-65 / CURB-65", "CHA2DS2-VASc"],
    correct: 2,
    explanation: "【要点】市中肺炎の重症度・入院要否判断には、簡便なCURB-65およびその外来版CRB-65が広く用いられる。\n【内容】CURB-65は意識障害(Confusion)、尿素(Urea>7)、呼吸数(≥30)、血圧(sBP<90 or dBP≤60)、年齢(≥65)の5項目。0〜1点は外来、2点は短期入院検討、3点以上は入院/重症評価の目安。より詳細なPSI(Pneumonia Severity Index)も予後予測に用いる。\n【注意】スコアは補助であり、酸素化・併存症・社会的背景を含む総合判断が必要。\n【誤答】GRACEはACS、CHA2DS2-VAScはAFの塞栓リスク、WellsはVTEの検査前確率評価に用いるもので、肺炎には使わない。",
    source: { title: "Update in Outpatient General Internal Medicine (Am J Med)", url: "https://www.amjmed.com/article/S0002-9343(26)00149-X/abstract?rss=yes" },
    tags: ["肺炎", "重症度評価", "外来"]
  },
  {
    id: "rv-afib-01",
    category: "review",
    difficulty: 1,
    added: "2026-07-15",
    question: "非弁膜症性心房細動の脳梗塞リスク評価に用いるスコアはどれか。",
    options: ["CHA2DS2-VASc", "qSOFA", "CURB-65", "MELD"],
    correct: 0,
    explanation: "【要点】非弁膜症性心房細動の脳梗塞リスク層別化にはCHA2DS2-VAScを用いる。\n【内容】心不全・高血圧・年齢≥75(2点)・糖尿病・脳卒中/TIA既往(2点)・血管疾患・年齢65-74・女性で構成。男性≥2点、女性≥3点で抗凝固(DOAC推奨)を考慮する。出血リスクはHAS-BLEDで別途評価し、修正可能因子(血圧・アルコール・併用薬)を是正する。\n【注意】高い出血リスクは抗凝固の禁忌ではなく、是正と慎重なモニタリングの根拠とする。\n【誤答】CURB-65は肺炎、MELDは肝疾患重症度/移植優先度、qSOFAは敗血症スクリーニングの指標。",
    source: { title: "General internal medicine reference (Am J Med)", url: "https://www.amjmed.com/article/S0002-9343(26)00149-X/abstract?rss=yes" },
    tags: ["心房細動", "抗凝固", "脳梗塞リスク"]
  },
  {
    id: "rv-dm-01",
    category: "review",
    difficulty: 2,
    added: "2026-07-15",
    question: "2型糖尿病+ASCVD/心不全/CKDを合併する患者の血糖降下薬選択で、HbA1cとは独立に臓器保護目的で優先されるクラスの組み合わせはどれか。",
    options: ["SGLT2阻害薬 と GLP-1受容体作動薬", "スルホニル尿素薬 と α-グルコシダーゼ阻害薬", "インスリン単独 と メグリチニド", "チアゾリジン薬 と DPP-4阻害薬"],
    correct: 0,
    explanation: "【要点】ASCVD・心不全・CKDを合併する2型糖尿病では、HbA1cとは独立に、臓器保護目的でSGLT2阻害薬とGLP-1受容体作動薬が優先される。\n【使い分け】SGLT2阻害薬は心不全入院とCKD進行の抑制に強く、GLP-1受容体作動薬はASCVDイベント抑制と体重減少に優れる。両者は作用機序が異なり併用も可能。メトホルミンは依然ベースだが、これらの臓器保護効果は血糖降下作用とは別枠で評価される。\n【実践】『どの臓器を守りたいか』で第2剤を選ぶ発想が現行の標準。\n【誤答】SU薬・α-GI、TZD・DPP-4阻害薬、インスリン・グリニドの組み合わせには確立した心腎保護のエビデンスがない。",
    source: { title: "CVOT summit report 2024 (PMC)", url: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC12048985/" },
    tags: ["糖尿病", "SGLT2阻害薬", "GLP-1", "臓器保護"]
  },
  {
    id: "rv-thyroid-01",
    category: "review",
    difficulty: 2,
    added: "2026-07-15",
    question: "無症候性の軽度潜在性甲状腺機能低下症(TSH 4.5-10 mU/L、fT4正常)の高齢者に対する近年の考え方として最も適切なのはどれか。",
    options: ["多くの例で直ちにレボチロキシンを開始せず経過観察・再検を行う", "全例で直ちにレボチロキシンを開始する", "抗甲状腺薬を開始する", "ヨウ素制限食を第一選択とする"],
    correct: 0,
    explanation: "【要点】高齢者の軽度潜在性甲状腺機能低下症(TSH 4.5〜10、fT4正常)は、多くの例で直ちにレボチロキシンを開始せず、再検・経過観察が妥当。\n【エビデンス】TRUST試験など複数のRCTで、この層へのレボチロキシン補充は症状・QOL・認知機能を改善しなかった。TSHは自然正常化することも多く、過剰治療は医原性甲状腺機能亢進(心房細動・骨粗鬆症)のリスクを招く。\n【治療を考慮する状況】TSH≥10、明確な症状、妊娠(希望含む)、若年例などでは補充を検討する。\n【誤答】全例で即開始は過剰治療。抗甲状腺薬は機能亢進症の薬で不適。ヨウ素制限は適応外。",
    source: { title: "Update in Outpatient General Internal Medicine (Am J Med)", url: "https://www.amjmed.com/article/S0002-9343(26)00149-X/abstract?rss=yes" },
    tags: ["甲状腺", "潜在性甲状腺機能低下症", "高齢者"]
  },
  {
    id: "rv-vitd-01",
    category: "review",
    difficulty: 2,
    added: "2026-07-15",
    question: "健常成人へのビタミンDサプリメントのルーチン投与について、近年の大規模試験(VITAL等)が示した骨折・心血管・がんへの効果に最も近いものはどれか。",
    options: ["がん死を確実に予防した", "骨折を半減させた", "一般集団での骨折・心血管・がんの明確な予防効果は示されなかった", "心筋梗塞を有意に減少させた"],
    correct: 2,
    explanation: "【要点】欠乏のない一般集団へのビタミンDルーチン補充は、骨折・心血管・癌の明確な予防効果を示さなかった。\n【エビデンス】VITAL試験(約2.6万人)ではがん・心血管の主要エンドポイントに差がなく、骨折(補助解析)や転倒予防でも一般集団での有意な便益は示されなかった。したがって無症状者への一律スクリーニング(25(OH)D測定)と補充は推奨されない。\n【適応】明らかな欠乏、吸収不良、骨粗鬆症治療中、特定のハイリスク群など、対象を絞って補充する。\n【誤答】骨折半減・がん死予防・心筋梗塞減少を示す確固たるデータはない。",
    source: { title: "Vitamin D screening/supplementation systematic review (PMC)", url: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC12395781/" },
    tags: ["ビタミンD", "サプリメント", "予防"]
  },
  {
    id: "cl-vte-01",
    category: "clinical",
    difficulty: 3,
    added: "2026-07-15",
    question: "誘因のない(unprovoked)近位DVT/PEを初回発症し、標準期間の抗凝固を終えた患者。延長治療を行う場合の近年の実践として妥当なものはどれか。",
    options: ["全例で通常用量を無期限継続する以外に選択肢はない", "抗血小板薬単独に切り替えるのが標準", "延長治療は一律禁忌", "出血リスクとのバランスを見て減量用量DOACでの延長を検討する"],
    correct: 3,
    explanation: "【要点】unprovoked(誘因不明)の近位DVT/PE初回例で標準期間の抗凝固を終えた後は、出血リスクとのバランスを見て減量用量DOACでの延長を検討する。\n【理由】誘因不明VTEは再発率が高く(1年で約10%、以後も蓄積)延長治療がしばしば適応。アピキサバン2.5mg×2やリバーロキサバン10mgの減量レジメンは、通常用量に近い再発予防を保ちつつ出血を抑えうる(AMPLIFY-EXT等)。\n【判断】出血リスク評価、患者希望、D-dimerや残存血栓などを踏まえ、継続の是非と用量を個別化し定期的に再評価する。\n【誤答】通常用量無期限一択ではなく、抗血小板薬単独は再発予防が劣り、延長治療が一律禁忌でもない。",
    source: { title: "Update in Outpatient General Internal Medicine 2025 (Am J Med)", url: "https://www.amjmed.com/article/S0002-9343(26)00149-X/abstract?rss=yes" },
    tags: ["VTE", "延長治療", "DOAC", "出血リスク"]
  },
  {
    id: "cl-obesity-01",
    category: "clinical",
    difficulty: 2,
    added: "2026-07-15",
    question: "BMI 34、2型糖尿病・HFpEFを合併する患者の体重・心血管管理に関して、近年エビデンスが拡大している薬剤クラスはどれか。",
    options: ["GLP-1受容体作動薬 / GIP-GLP-1受容体作動薬(インクレチン関連薬)", "食欲増進薬", "β遮断薬単独", "利尿薬単独"],
    correct: 0,
    explanation: "【要点】肥満+2型糖尿病+HFpEFの患者では、インクレチン関連薬(GLP-1受容体作動薬、GIP/GLP-1受容体作動薬)のエビデンスが拡大している。\n【エビデンス】セマグルチドは肥満のSELECTで心血管イベントを抑制、STEP-HFpEFでHFpEF症状を改善、FLOWでCKDに有益。チルゼパチド(GIP/GLP-1)は大幅な減量とSUMMITでHFpEFアウトカム改善を示した。肥満を軸に心・腎・代謝を一体で管理する流れが強まっている。\n【注意】消化器症状や導入時の用量漸増、併用薬(インスリン/SU)の低血糖に留意。\n【誤答】利尿薬・β遮断薬単独はこの文脈の体重/イベント管理の主役ではなく、食欲増進薬は逆効果。",
    source: { title: "CVOT summit report 2024 (PMC)", url: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC12048985/" },
    tags: ["肥満", "GLP-1", "心腎代謝", "HFpEF"]
  },
  {
    id: "rv-statin-01",
    category: "review",
    difficulty: 1,
    added: "2026-07-15",
    question: "確立したASCVD(心筋梗塞既往等)の二次予防における脂質管理の基本方針として正しいものはどれか。",
    options: ["LDL低下は予後に無関係", "低強度スタチンで十分", "高強度スタチンを基本とし、目標未達ならエゼチミブ・PCSK9阻害薬等を追加", "スタチンは不要で食事療法のみ"],
    correct: 2,
    explanation: "【要点】確立したASCVD(心筋梗塞既往など)の二次予防では高強度スタチンが基本で、目標未達ならエゼチミブ、PCSK9阻害薬、ベンペド酸などを追加する。\n【エビデンス】'lower is better'が一貫して支持され、多くのガイドラインでLDL目標<70mg/dL(超高リスクでは<55mg/dL)を掲げる。IMPROVE-IT(エゼチミブ)、FOURIER/ODYSSEY(PCSK9阻害薬)が上乗せ効果を示した。\n【実践】まず高強度スタチンを最大耐用量で、忍容性が問題ならエゼチミブ併用や中強度+上乗せで対応する。\n【誤答】食事療法のみ・低強度で十分は二次予防では不足。『LDL低下は予後に無関係』は明確に誤り。",
    source: { title: "General internal medicine lipid management (Am J Med)", url: "https://www.amjmed.com/article/S0002-9343(26)00149-X/abstract?rss=yes" },
    tags: ["脂質", "スタチン", "二次予防", "ASCVD"]
  },
  {
    id: "cl-uti-01",
    category: "clinical",
    difficulty: 1,
    added: "2026-07-15",
    question: "無症候性細菌尿(asymptomatic bacteriuria)への抗菌薬治療が推奨される代表的な状況はどれか。",
    options: ["糖尿病患者全般", "妊婦、および泌尿器的処置(粘膜出血を伴う)前", "尿カテーテル留置中の全例", "高齢者施設入所者全般"],
    correct: 1,
    explanation: "【要点】無症候性細菌尿は原則として治療しない。抗菌薬治療が推奨される代表的例外は妊婦と、粘膜出血を伴う泌尿器処置の前である。\n【理由】妊娠では腎盂腎炎・早産リスクの低減、侵襲的泌尿器処置前では菌血症予防の観点で治療の便益が示されている。それ以外(高齢者、施設入所者、糖尿病、カテーテル留置)では、症状がなければ治療は予後を改善せず、耐性菌やC. difficile感染のリスクを増やす。\n【実践】高齢者の非特異的症状だけで尿培養陽性=治療としないことが、抗菌薬適正使用の要点。\n【誤答】高齢者一般・カテーテル留置全例・糖尿病一般は治療対象ではない。",
    source: { title: "Update in Outpatient General Internal Medicine (Am J Med)", url: "https://www.amjmed.com/article/S0002-9343(26)00149-X/abstract?rss=yes" },
    tags: ["感染症", "無症候性細菌尿", "抗菌薬適正使用"]
  },
  {
    id: "cl-ppi-01",
    category: "clinical",
    difficulty: 2,
    added: "2026-07-15",
    question: "長期PPI内服中の高齢者。適応を再評価し減量・中止(deprescribing)を検討する根拠として最も適切なものはどれか。",
    options: ["PPIは有害事象が全くないため常に継続", "全てのPPIを直ちに一律中止すべき", "PPIはH2受容体拮抗薬より必ず劣る", "明確な継続適応がない例では、長期使用に伴う潜在的有害事象を踏まえ減量・中止を検討"],
    correct: 3,
    explanation: "【要点】長期PPI内服者では適応を再評価し、明確な継続適応がなければ段階的な減量・中止(deprescribing)を検討する。\n【背景】PPIは有用だが、しばしば漫然と継続される。長期使用は骨折・低マグネシウム/B12欠乏・腸管感染・肺炎などとの関連が報告される(多くは観察研究で因果は限定的だが、不要な曝露は避けるべき)。\n【継続すべき適応】重症逆流性食道炎、Barrett食道、消化管出血の二次予防、NSAID/抗血小板薬併用の高リスク例など。\n【方法】適応のない例は減量→隔日→中止と段階的に行い、反跳性胃酸分泌に伴う一過性症状に備える。\n【誤答】『有害事象皆無で常に継続』『一律即中止』『必ずH2RA劣位』はいずれも不正確。",
    source: { title: "Update in Outpatient General Internal Medicine (Am J Med)", url: "https://www.amjmed.com/article/S0002-9343(26)00149-X/abstract?rss=yes" },
    tags: ["PPI", "deprescribing", "ポリファーマシー"]
  },
  {
    id: "gl-dm-01",
    category: "guideline",
    difficulty: 2,
    added: "2026-07-15",
    question: "近年の糖尿病診療ガイドライン(ADA Standards of Care等)における薬物選択の基本的な枠組みとして正しいものはどれか。",
    options: ["初診時から必ずインスリンを導入する", "HbA1cだけでなく併存疾患(ASCVD/HF/CKD)や体重・低血糖リスクを軸に個別化する", "全例でメトホルミン→SU薬の順で固定する", "薬剤選択はHbA1cのみで決定する"],
    correct: 1,
    explanation: "【要点】現行のADA Standards of Careでは、HbA1c目標だけでなく併存疾患(ASCVD/心不全/CKD)・体重・低血糖リスク・費用/アクセスを踏まえて薬剤を個別化する。\n【枠組み】臓器保護が必要ならHbA1cに関わらずSGLT2阻害薬(心不全・CKD)やGLP-1受容体作動薬(ASCVD・肥満)を優先。低血糖回避や体重管理も選択に反映し、メトホルミンは費用対効果に優れるベース薬として位置づけられる。\n【実践】『まず患者の合併症プロファイルを見て、次に血糖』という順序が現代の標準的思考。\n【誤答】メトホルミン→SU固定、初診時からの一律インスリン、HbA1cのみでの決定は、いずれも現行の個別化アプローチに反する。",
    source: { title: "CVOT summit report 2024 (PMC)", url: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC12048985/" },
    tags: ["糖尿病", "ADA", "個別化治療"]
  },
  {
    id: "jr-empakidney-01",
    category: "journal",
    difficulty: 2,
    added: "2026-07-16",
    question: "EMPA-KIDNEY試験(エンパグリフロジン vs プラセボ)がSGLT2阻害薬のCKDへの適応について示した最も重要な点はどれか。",
    options: ["糖尿病を合併するCKDでのみ有効だった", "糖尿病の有無にかかわらずCKD進行/心血管死の複合を有意に低下させた", "eGFRが45未満の症例では効果がなかった", "尿蛋白のない症例ではむしろ有害だった"],
    correct: 1,
    explanation: "【要点】エンパグリフロジンはCKD進行/心血管死の複合を有意に低下させ、効果は糖尿病の有無を問わなかった。\n【エビデンス】eGFR20〜45、またはeGFR45〜90かつUACR≥200の6609例を対象。主要アウトカムは13.1% vs 16.9%(HR 0.72)で約28%減。糖尿病の有無・eGFR層によらず一貫し、全入院も減少した。\n【臨床応用】SGLT2阻害薬の腎保護は糖尿病性腎症に限らず、非糖尿病CKDにも広がった。導入初期のeGFR低下(initial dip)は可逆性で継続してよい。\n【誤答】糖尿病限定・eGFR45未満で無効・尿蛋白なしで有害、はいずれも試験結果と異なる。",
    source: { title: "Empagliflozin in Patients with Chronic Kidney Disease (EMPA-KIDNEY, NEJM 2023)", url: "https://www.nejm.org/doi/full/10.1056/NEJMoa2204233" },
    tags: ["CKD", "SGLT2阻害薬", "腎保護", "非糖尿病"]
  },
  {
    id: "jr-surmountosa-01",
    category: "journal",
    difficulty: 2,
    added: "2026-07-16",
    question: "中等症〜重症の閉塞性睡眠時無呼吸(OSA)+肥満の成人を対象としたSURMOUNT-OSA試験で、チルゼパチドが示した結果はどれか。",
    options: ["AHI(無呼吸低呼吸指数)には変化がなかった", "体重は減ったがAHIはむしろ悪化した", "AHIを有意に低下させ、相当数が疾患消失基準を満たした", "CPAP併用者では全く無効だった"],
    correct: 2,
    explanation: "【要点】GIP/GLP-1受容体作動薬チルゼパチドは、肥満を伴う中等症〜重症OSAのAHIを有意に低下させた。\n【エビデンス】52週の2試験(CPAP非使用/使用)で、最高用量群の約43〜51%が疾患消失基準を満たし、体重・低酸素負荷・hsCRP・収縮期血圧・睡眠関連QOLも改善。\n【臨床応用】肥満を機序に含むOSAでは、減量薬が睡眠時無呼吸そのものの治療選択肢になりうる。CPAPや生活指導を置き換えるかは個別判断で、消化器症状に留意する。\n【誤答】AHI不変・悪化・CPAP併用者で無効は、いずれも結果と異なる。",
    source: { title: "Tirzepatide for the Treatment of Obstructive Sleep Apnea and Obesity (SURMOUNT-OSA, NEJM 2024)", url: "https://www.nejm.org/doi/10.1056/NEJMoa2404881" },
    tags: ["OSA", "肥満", "チルゼパチド", "インクレチン"]
  },
  {
    id: "gl-crc-01",
    category: "guideline",
    difficulty: 1,
    added: "2026-07-16",
    question: "平均的リスクの成人に対する大腸癌スクリーニング開始年齢について、2021年のUSPSTF勧告はどう変更したか。",
    options: ["45歳から開始する(45〜49歳はGrade B推奨)", "40歳から開始する", "従来どおり50歳からで変更はない", "55歳からで十分とした"],
    correct: 0,
    explanation: "【要点】2021年USPSTFは平均リスク者の大腸癌スクリーニング開始年齢を50歳から45歳へ引き下げた(45〜49歳はGrade B)。\n【背景】若年発症大腸癌の増加を受けた変更で、中等度の純便益があると判断。50〜75歳は引き続き強く推奨(Grade A)。\n【臨床応用】高感度便潜血、大腸内視鏡、CTコロノグラフィ、S状結腸鏡のいずれも許容される。方法は患者の希望・アクセスで選び、陽性の便検査は内視鏡でフォローする。\n【誤答】40歳/55歳開始や『50歳から変更なし』は現行勧告と異なる。",
    source: { title: "Screening for Colorectal Cancer: USPSTF Recommendation Statement (JAMA 2021)", url: "https://jamanetwork.com/journals/jama/fullarticle/2779985" },
    tags: ["がん検診", "大腸癌", "USPSTF", "予防"]
  },
  {
    id: "cl-cap-abx-01",
    category: "clinical",
    difficulty: 2,
    added: "2026-07-16",
    question: "外来の市中肺炎で臨床的に安定した成人の抗菌薬投与期間について、近年のエビデンスおよびATSの方向性として適切なものはどれか。",
    options: ["最低14日間は必要である", "症状が完全消失するまで無期限に継続する", "一律10日間が標準である", "臨床的に安定すれば短期間(概ね3〜5日)で十分"],
    correct: 3,
    explanation: "【要点】臨床的安定に達した市中肺炎では、短期間(概ね3〜5日、最短3日)の抗菌薬で十分で、漫然とした長期投与は不要。\n【エビデンス】複数のRCT・メタ解析が短期(3〜7日)の長期(>7日)に対する非劣性を示し、ATSガイドラインも安定例で5日未満を提案。短縮は耐性・有害事象・費用を減らす。\n【臨床応用】解熱・バイタル安定・経口摂取可を目安に、安定後さらに数日で終了を検討する。安定化しない・膿胸や特殊病原体では延長する。\n【誤答】14日以上・無期限・一律10日は過剰治療で、抗菌薬適正使用に反する。",
    source: { title: "Diagnosis and Management of Community-acquired Pneumonia: ATS Clinical Practice Guideline", url: "https://academic.oup.com/ajrccm/article/212/1/24/8435770" },
    tags: ["肺炎", "抗菌薬適正使用", "投与期間", "外来"]
  },
  {
    id: "gl-rsv-01",
    category: "guideline",
    difficulty: 1,
    added: "2026-07-16",
    question: "2024年の米国ACIPによる成人へのRSVワクチン推奨として正しいものはどれか。",
    options: ["全成人に毎年接種する", "60歳以上の全員に毎年接種する", "75歳以上の全員、および60〜74歳のハイリスク者に単回接種", "高齢者への接種は推奨されない"],
    correct: 2,
    explanation: "【要点】2024年ACIPは、75歳以上の全員と、重症RSVリスクの高い60〜74歳に、RSVワクチンの単回接種を推奨した。\n【背景】従来の『60歳以上で共有意思決定』から、年齢ベースの明確な推奨へ変更。RSVの疾病負荷・ワクチン有効性・費用対効果の解析に基づく。\n【臨床応用】現時点では生涯に1回の接種で、既接種者への追加は非推奨。Arexvy/Abrysvo/mResviaのいずれも使用可。\n【誤答】『全成人に毎年』『60歳以上に毎年』は誤り(毎年接種ではない)。高齢者に非推奨も誤り。",
    source: { title: "Use of RSV Vaccines in Adults Aged ≥60 Years: Updated ACIP Recommendations, 2024 (MMWR)", url: "https://www.cdc.gov/mmwr/volumes/73/wr/mm7332e1.htm" },
    tags: ["ワクチン", "RSV", "高齢者", "予防接種"]
  },
  {
    id: "cl-diuretic-01",
    category: "clinical",
    difficulty: 2,
    added: "2026-07-16",
    question: "高齢高血圧患者を対象にクロルタリドンとヒドロクロロチアジド(HCTZ)を比較したDiuretic Comparison Project(DCP)の結果として正しいものはどれか。",
    options: ["主要心血管複合アウトカムに有意差はなかった", "クロルタリドンが心血管死を半減させた", "HCTZが脳卒中を有意に増やした", "クロルタリドンで全死亡が有意に増加した"],
    correct: 0,
    explanation: "【要点】DCPでは、クロルタリドンとHCTZの主要心血管複合アウトカムに有意差はなかった。\n【エビデンス】既にHCTZを内服する65歳以上の退役軍人13,523例を、HCTZ継続 vs クロルタリドン切替に無作為化(中央値2.4年)。心筋梗塞・脳卒中・心不全入院・不安定狭心症の血行再建・非癌死の複合は同等。ただしクロルタリドン群で低カリウム血症がやや多かった。\n【臨床応用】どちらのサイアザイド系でも心血管予防効果は概ね同等。電解質(特に低K・低Na)のモニタリングは重要。\n【誤答】心血管死半減・HCTZで脳卒中増加・クロルタリドンで全死亡増加は、いずれも示されていない。",
    source: { title: "Chlorthalidone vs. Hydrochlorothiazide for Hypertension-Cardiovascular Events (DCP, NEJM 2022)", url: "https://pubmed.ncbi.nlm.nih.gov/36516076/" },
    tags: ["高血圧", "利尿薬", "サイアザイド", "電解質"]
  },
  {
    id: "jr-mash-01",
    category: "journal",
    difficulty: 2,
    added: "2026-07-15",
    question: "ESSENCE試験(セマグルチド2.4mg vs プラセボ、MASH+F2-F3線維化)の72週での主要組織学的アウトカムはどれか。",
    options: ["肝線維化・脂肪肝炎ともに改善しなかった", "体重は減少したが肝組織像は不変だった", "脂肪肝炎の消失と線維化改善のいずれもプラセボより高率だった", "線維化はむしろ悪化した"],
    correct: 2,
    explanation: "【要点】セマグルチド2.4mgは、MASH+中等度〜進行線維化(F2-F3)の肝組織像をプラセボより有意に改善した。\n【エビデンス】ESSENCE第3相(72週中間解析)で、脂肪肝炎の悪化なしの線維化改善が36.8% vs 22.4%、脂肪肝炎の消失+線維化改善が32.7% vs 16.1%。体重・肝酵素・代謝指標も改善した。2025年、FDAはMASHの中等度〜進行線維化に対しセマグルチドを承認。\n【臨床応用】肥満・2型糖尿病を伴うMASHでは、減量を軸に肝を含めた心・腎・代謝の包括管理の選択肢となる。導入時は消化器症状と用量漸増に留意。\n【誤答】改善なし・組織像不変・線維化悪化は、いずれも試験結果と逆である。",
    source: { title: "Phase 3 Trial of Semaglutide in Metabolic Dysfunction-Associated Steatohepatitis (ESSENCE, NEJM 2025)", url: "https://www.nejm.org/doi/abs/10.1056/NEJMoa2413258" },
    tags: ["MASH", "セマグルチド", "GLP-1", "肝線維化"]
  },
  {
    id: "rv-mash-01",
    category: "review",
    difficulty: 2,
    added: "2026-07-15",
    question: "非硬変性MASH(中等度〜進行線維化)に対し2024年に初めてFDA承認された経口薬レスメチロムの薬理学的分類はどれか。",
    options: ["GLP-1受容体作動薬", "肝選択的 甲状腺ホルモン受容体β(THR-β)作動薬", "SGLT2阻害薬", "PPAR-γ作動薬(チアゾリジン)"],
    correct: 1,
    explanation: "【要点】レスメチロムは肝選択的な甲状腺ホルモン受容体β(THR-β)作動薬で、2024年3月にMASH(中等度〜進行線維化)への初のFDA承認薬となった。\n【エビデンス】MAESTRO-NASH(第3相、F1B-F3の約966例)で、脂肪肝炎の消失(線維化悪化なし)が80mg 25.9%/100mg 29.9% vs プラセボ9.7%、線維化1段階以上改善が24〜25% vs 14.2%。\n【臨床応用】肝でのTHR-β活性化により脂質・脂肪化を改善。生活習慣是正が基盤で、対象は非硬変性の線維化例。硬変例は適応外。\n【誤答】GLP-1受容体作動薬・SGLT2阻害薬・PPAR-γ作動薬はいずれも別クラスで、レスメチロムには当たらない。",
    source: { title: "First FDA-Approved NASH Treatment: MAESTRO-NASH Trial (ACG EBGI)", url: "https://gi.org/journals-publications/ebgi/leff_rich_april2024/" },
    tags: ["MASH", "レスメチロム", "THR-β", "肝線維化"]
  },
  {
    id: "jr-colch-01",
    category: "journal",
    difficulty: 3,
    added: "2026-07-15",
    question: "急性心筋梗塞後の患者を対象に低用量コルヒチンをプラセボと比較した大規模RCT(CLEAR SYNERGY/OASIS-9)の主要結果はどれか。",
    options: ["主要心血管イベントを約31%減少させた", "全死亡を有意に増加させた", "脳卒中のみを有意に減少させた", "主要心血管複合アウトカムに有意差を認めなかった"],
    correct: 3,
    explanation: "【要点】CLEAR SYNERGY(OASIS-9)では、急性MI後の低用量コルヒチン(0.5mg/日)はプラセボに対し主要心血管複合アウトカムを有意に減らさなかった。\n【エビデンス】約7,062例、中央値3.5年で、CV死/MI/脳卒中/虚血による血行再建は9.1% vs 9.3%と有意差なし。CRPはコルヒチン群でより低下したが転帰に結びつかなかった。先行のCOLCOT/LoDoCo2の陽性結果とは対照的で、解釈に議論がある。\n【臨床応用】MI後の抗炎症目的でのコルヒチン一律投与は支持されにくくなり、適応は個別・慎重に判断する。\n【誤答】31%減少・全死亡増加・脳卒中のみ減少は、いずれも本試験の結果と異なる。",
    source: { title: "Colchicine Surprise: No Help Post-MI, Large CLEAR SYNERGY Trial (tctmd)", url: "https://www.tctmd.com/news/colchicine-surprise-no-help-post-mi-large-clear-synergy-trial-shows" },
    tags: ["心筋梗塞", "コルヒチン", "抗炎症", "二次予防"]
  },
  {
    id: "gl-dm-02",
    category: "guideline",
    difficulty: 2,
    added: "2026-07-15",
    question: "米国内科学会(ACP)の2型糖尿病の血糖管理ガイダンス(HbA1c目標)に関する立場として正しいものはどれか。",
    options: ["多くの成人でHbA1c 7〜8%を目標とし、過度に厳格な管理(<6.5%等)は避ける", "全例でHbA1c<6.5%を目標とする", "HbA1c目標は不要で薬剤数のみで管理する", "高齢者ほど厳格な目標を推奨する"],
    correct: 0,
    explanation: "【要点】ACPは、多くの2型糖尿病成人でHbA1c 7〜8%を目標とし、<6.5%のような過度に厳格な管理は避けるべきと提言している(de-emphasis)。\n【背景】ACCORD等で厳格管理が低血糖・死亡リスクを増やす一方、大血管イベントを明確に減らさなかったことを踏まえる。近年の更新では、SGLT2阻害薬・GLP-1受容体作動薬を臓器保護目的で治療選択に加えることも支持している。\n【臨床応用】平均余命が限られる・併存症の多い高齢者ではさらに緩やかな目標とし、低血糖回避を優先。目標は個別化する。\n【誤答】全例<6.5%や高齢者での厳格化は低血糖・過剰治療の観点で不適切。目標の放棄も誤り。",
    source: { title: "ACP Reaffirms De-emphasis on Glucose Control and Adds New Treatments for Type 2 Diabetes (AFP POEM 2026)", url: "https://www.aafp.org/afp/2026/0500/poems-glucose-control-type-2-diabetes" },
    tags: ["糖尿病", "ACP", "HbA1c目標", "個別化治療"]
  },
  {
    id: "cl-gout-01",
    category: "clinical",
    difficulty: 2,
    added: "2026-07-15",
    question: "痛風発作を年2回以上繰り返す患者への尿酸降下療法(ULT)の考え方として、近年広く支持される方針はどれか。",
    options: ["尿酸値は測らず臨床症状のみで用量を決める", "急性発作の最中に高用量で開始して発作を早く抑える", "頻回発作・痛風結節・尿路結石等では血清尿酸<6.0mg/dLを目標にアロプリノール等を漸増(treat-to-target)", "ULTは一度開始したら数か月で必ず中止する"],
    correct: 2,
    explanation: "【要点】頻回発作(目安 年2回以上)、痛風結節、尿路結石、CKD合併などでは、血清尿酸<6.0mg/dLを目標にULTを漸増する treat-to-target 戦略が広く支持される(ACR 2020)。\n【エビデンス】尿酸を持続的に<6.0mg/dLに保つと発作・結節が減少する。第一選択はアロプリノールで少量から漸増し、開始初期はコルヒチン等で数か月の発作予防を併用する。ACPは初回・稀な発作での一律開始には慎重で、患者と利害を相談する立場。\n【臨床応用】ULTの導入は発作沈静後が原則だが、既にULT中であれば発作時も中断しない。\n【誤答】発作中の高用量開始や数か月での一律中止は不適切で、尿酸値を無視した用量調整も推奨されない。",
    source: { title: "2020 American College of Rheumatology Guideline for the Management of Gout (PMC)", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC10563586/" },
    tags: ["痛風", "尿酸降下療法", "treat-to-target", "アロプリノール"]
  },
  {
    id: "jr-vte-02",
    category: "journal",
    difficulty: 2,
    added: "2026-07-15",
    question: "誘因のある(provoked)VTEで持続する危険因子を持つ患者を対象に、初期抗凝固後の延長治療を検討したHI-PRO試験(NEJM)の結果はどれか。",
    options: ["延長治療でも再発は減らせなかった", "低用量アピキサバン12か月延長で再発が有意に減少し、大出血は少なかった", "延長治療で大出血が大幅に増え試験が中止された", "抗血小板薬への切り替えが最も有効だった"],
    correct: 1,
    explanation: "【要点】HI-PRO試験は、誘因ありVTEでも持続的な危険因子を持つ高リスク例では、低用量アピキサバン(2.5mg×2)の12か月延長が再発を有意に減らし、大出血が少ないことを示した。\n【エビデンス】600例で、症候性再発が1.3%(アピキサバン) vs 10.0%(プラセボ)(HR 0.13)。大出血はアピキサバン群1例のみ。プラセボ群の高い再発率は『provoked/unprovokedの二分法』の限界を示唆する。\n【臨床応用】一過性の誘因であっても、肥満・がん・慢性炎症など持続する因子があれば延長治療を個別に検討する。\n【誤答】再発を減らせない・大出血で中止・抗血小板薬への切替が最良は、いずれも試験結果と異なる。",
    source: { title: "Extended-Duration Low-Intensity Apixaban in Provoked VTE with Enduring Risk Factors (HI-PRO, tctmd/NEJM 2025)", url: "https://www.tctmd.com/news/hi-pro-oral-apixaban-1-year-protective-safe-provoked-vte-patients" },
    tags: ["VTE", "アピキサバン", "延長治療", "provoked"]
  },
  {
    id: "jr-bb-01",
    category: "journal",
    difficulty: 2,
    added: "2026-07-16",
    question: "REDUCE-AMI試験(急性心筋梗塞後・LVEF≥50%)で、長期β遮断薬 vs 非投与を比較した主要結果はどれか。",
    options: ["β遮断薬が全死亡を有意に減少させた", "全死亡+新規心筋梗塞の複合に有意差はなかった", "β遮断薬が心不全入院を半減させた", "β遮断薬で新規心筋梗塞がむしろ増加した"],
    correct: 1,
    explanation: "【要点】REDUCE-AMIでは、早期に冠動脈造影を受けLVEF≥50%が保たれた急性MI後患者で、長期β遮断薬は全死亡+新規MIの複合を有意に減らさなかった。\n【エビデンス】約5,020例(大半がスウェーデン)、中央値3.5年で、主要イベントは7.9%(β遮断薬) vs 8.3%(非投与)(HR 0.96、p=0.64)。再灌流時代のEF保持例では、β遮断薬のルーチン長期投与の恩恵は乏しい可能性を示す。\n【臨床応用】EF保持のMI後で忍容性不良や副作用がある場合、継続の要否を個別に再評価しうる。EF低下例・HFrEFでは従来どおり適応。\n【誤答】全死亡減少・心不全入院半減・MI増加は、いずれも本試験の結果と異なる。",
    source: { title: "REDUCE-AMI: Long-term Beta-blocker after AMI and Preserved LVEF (ACC 2024 / NEJM)", url: "https://www.pcronline.com/News/Congress-coverages/ACC/2024/REDUCE-AMI-Trial-Long-term-beta-blocker-treatment-after-AMI-and-preserved-left-ventricular-ejection-fraction" },
    tags: ["心筋梗塞", "β遮断薬", "EF保持", "二次予防"]
  },
  {
    id: "jr-pad-01",
    category: "journal",
    difficulty: 2,
    added: "2026-07-16",
    question: "2型糖尿病+症候性末梢動脈疾患(間欠性跛行)を対象としたSTRIDE試験で、セマグルチドが示した主要アウトカムはどれか。",
    options: ["最大歩行距離は不変だった", "下肢切断率をむしろ増やした", "最大歩行距離をプラセボより有意に改善した", "血糖は下がったが歩行機能は悪化した"],
    correct: 2,
    explanation: "【要点】STRIDE試験で、セマグルチド1mgは2型糖尿病+症候性PAD(間欠性跛行)患者の最大歩行距離をプラセボより有意に改善した。\n【エビデンス】792例、52週で、最大歩行距離が約13%の上乗せ改善(治療差の中央値 約26m)。無痛歩行距離やVascuQoL-6によるQOLも有意に改善した。有害事象は主に消化器症状。\n【臨床応用】PADの機能障害に対し、従来の運動療法・危険因子管理に加えGLP-1受容体作動薬が選択肢となりうる。ABIそのものの改善を示す試験ではなく、機能・症状面の改善が主眼。\n【誤答】歩行距離が不変・悪化や切断率の増加は、いずれも試験結果と異なる。",
    source: { title: "Semaglutide and Walking Capacity in Symptomatic PAD and Type 2 Diabetes (STRIDE, Lancet 2025)", url: "https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(25)00509-4/abstract" },
    tags: ["末梢動脈疾患", "セマグルチド", "GLP-1", "間欠性跛行"]
  },
  {
    id: "jr-ckd-02",
    category: "journal",
    difficulty: 3,
    added: "2026-07-16",
    question: "2型糖尿病+CKD(アルブミン尿)患者で、フィネレノンとエンパグリフロジンの同時併用 vs 各単独を比較したCONFIDENCE試験の主要結果はどれか。",
    options: ["併用は単独より高K血症を著明に増やし中止された", "併用と単独でUACR低下に差はなかった", "エンパグリフロジン単独が最も強くUACRを下げた", "併用が各単独よりUACRを有意に大きく低下させた"],
    correct: 3,
    explanation: "【要点】CONFIDENCE試験は、2型糖尿病+CKD(アルブミン尿)で、フィネレノン+エンパグリフロジンの同時併用が各単独よりUACRを有意に大きく低下させることを示した。\n【エビデンス】約800例を3群(フィネレノン/エンパグリフロジン/併用)に割付。180日でUACRは併用がフィネレノン単独より約29%、エンパグリフロジン単独より約32%大きく低下(併用で約52%減)。重篤な高K血症の増加は目立たなかった。\n【臨床応用】残余アルブミン尿のある例で、両薬の早期併用が腎保護の上乗せ戦略となりうる。導入後もカリウム・腎機能のモニタリングは行う。\n【誤答】差なし・エンパ単独が最強・高K血症で中止は、いずれも試験結果と異なる。",
    source: { title: "CONFIDENCE Trial: Finerenone plus Empagliflozin in CKD and T2D (ISN / NEJM 2025)", url: "https://www.theisn.org/blog/2025/09/15/confidence-trial-dual-therapy-shows-promise-for-ckd-and-diabetes/" },
    tags: ["CKD", "フィネレノン", "SGLT2阻害薬", "アルブミン尿"]
  },
  {
    id: "gl-pcv-01",
    category: "guideline",
    difficulty: 1,
    added: "2026-07-16",
    question: "2024年10月のACIP改訂による成人肺炎球菌結合型ワクチン(PCV)接種の年齢基準として正しいものはどれか。",
    options: ["PCV未接種の50歳以上の全成人に単回接種を推奨", "65歳以上のみに接種を推奨", "全成人に毎年接種を推奨", "成人への肺炎球菌ワクチンは非推奨"],
    correct: 0,
    explanation: "【要点】2024年10月、ACIPはPCV未接種の50歳以上の全成人に肺炎球菌結合型ワクチン(PCV)の単回接種を推奨した(従来の65歳以上から引き下げ)。\n【内容】選択肢はPCV20またはPCV21の単回、あるいはPCV15→1年後にPPSV23。19〜49歳のリスク保有者への推奨は変更なし。年齢引き下げは疾病負荷とワクチンの費用対効果の解析に基づく。\n【臨床応用】50歳以上で接種歴不明・未接種なら1回のPCVを検討する。既にPCV13等の接種歴がある場合は、個別の接種歴に応じて判断する。\n【誤答】65歳以上のみ・毎年接種・非推奨は、いずれも現行のACIP推奨と異なる。",
    source: { title: "Expanded Recommendations for Pneumococcal Conjugate Vaccines Among Adults Aged ≥50 Years (ACIP, MMWR 2024/2025)", url: "https://www.cdc.gov/mmwr/volumes/74/wr/mm7401a1.htm" },
    tags: ["ワクチン", "肺炎球菌", "ACIP", "予防接種"]
  },
  {
    id: "cl-pcnallergy-01",
    category: "clinical",
    difficulty: 2,
    added: "2026-07-16",
    question: "「ペニシリンアレルギー」の記載がある低リスク患者への近年のアプローチとして、PALACE試験等が支持する方針はどれか。",
    options: ["全例で生涯ペニシリン系を回避する", "全例にまず皮膚テストを行わなければ投与できない", "低リスク例(PEN-FASTスコアが低い等)では直接経口負荷試験でラベルを解除できる", "アナフィラキシー既往例でも外来で経口負荷して差し支えない"],
    correct: 2,
    explanation: "【要点】自己申告のペニシリンアレルギーの多くは真のアレルギーでなく(実際に反応するのは概ね<5%)、低リスク例では直接経口負荷試験(DOC)でラベルを安全に解除できる。\n【エビデンス】PALACE試験は、臨床判断ルールで低リスクと判定した患者で、皮膚テストを省いた直接経口負荷が有効かつ安全と示した。PEN-FASTスコアが低い(目安<3)例が低リスクの目安で、プライマリ・ケアでの実施可能性も報告されている。\n【臨床応用】不要なアレルギーラベルは広域抗菌薬の使用・耐性・コスト増につながるため、適切な患者では積極的に見直す。\n【誤答】全例回避や全例で皮膚テスト必須は過剰。重症・アナフィラキシー既往は高リスクで、安易な外来経口負荷は不適切。",
    source: { title: "Efficacy of a Clinical Decision Rule to Enable Direct Oral Challenge in Low-Risk Penicillin Allergy (PALACE, JAMA Intern Med)", url: "https://jamanetwork.com/journals/jamainternalmedicine/fullarticle/2806976" },
    tags: ["薬剤アレルギー", "ペニシリン", "抗菌薬適正使用", "delabeling"]
  },
  {
    id: "rv-lpa-01",
    category: "review",
    difficulty: 2,
    added: "2026-07-16",
    question: "リポプロテイン(a)〔Lp(a)〕の測定に関する近年の一般的な考え方として最も適切なものはどれか。",
    options: ["生活習慣改善で大きく変動するため毎年測定する", "主に遺伝的に規定され、原則として生涯に1回の測定で心血管リスク評価に有用", "測定してもリスク層別化には役立たない", "スタチンで著明に低下するため治療効果判定に用いる"],
    correct: 1,
    explanation: "【要点】Lp(a)は80%以上が遺伝的に規定され加齢・生活習慣で大きく変わらないため、原則として生涯に1回の測定で心血管リスク評価に有用とされる(NLA/EAS等のガイダンス)。\n【意義】高Lp(a)はASCVDの独立した因果的危険因子で、境界〜中等度リスク例の再分類や、より積極的な危険因子管理の動機づけに使える。\n【注意】近年、実臨床では個体内変動が想定より大きく再分類が起こりうるとの報告もあり、値は臨床全体の文脈で解釈する。Lp(a)標的治療薬(RNA医薬等)は開発段階。\n【誤答】毎年測定や治療効果判定への使用は不要/不適切で、スタチンでLp(a)は大きく下がらない。『役立たない』も誤り。",
    source: { title: "Lipoprotein(a) in Clinical Practice: What Clinicians Need to Know (Cleve Clin J Med 2025)", url: "https://www.ccjm.org/content/92/11/679" },
    tags: ["脂質", "Lp(a)", "心血管リスク", "予防"]
  },
  {
    id: "rv-gerd-01",
    category: "review",
    difficulty: 1,
    added: "2026-07-16",
    question: "典型的な胸やけ・逆流症状があり警告徴候(嚥下障害・体重減少・出血・貧血等)のない成人GERDへの初期対応として、標準的な方針はどれか。",
    options: ["全例でまず上部消化管内視鏡を行う", "初期から外科的噴門形成術を検討する", "生活習慣是正とPPIの8週間経験的投与を行い、その後症状を再評価する", "H2受容体拮抗薬を生涯継続する"],
    correct: 2,
    explanation: "【要点】警告徴候のない典型的GERDでは、生活習慣是正+PPIの8週間経験的投与を行い、再評価する方針が標準(JAMA 2020レビュー)。\n【背景/エビデンス】GERDは高所得国の成人の約20%が罹患。PPIへの症状反応は診断の感度71%・特異度44%と限定的で、反応の有無だけでGERDを確定できず過剰診断に注意する。\n【臨床応用】8週後に症状消失なら減量・中止を試み、必要時は最少有効量で維持。嚥下障害・体重減少・出血・貧血・胸痛や難治例では内視鏡を行う。\n【誤答】全例の即内視鏡や初期からの手術は不要で、H2RAの漫然とした生涯継続も不適切。",
    source: { title: "Gastroesophageal Reflux Disease: A Review (JAMA 2020)", url: "https://jamanetwork.com/journals/jama/article-abstract/2774414" },
    tags: ["GERD", "PPI", "消化器", "外来"]
  },
  {
    id: "rv-oa-01",
    category: "review",
    difficulty: 1,
    added: "2026-07-16",
    question: "膝・股関節の変形性関節症(OA)に対する中核的治療として、Lancetのレビュー等が第一に位置づけるのはどれか。",
    options: ["運動療法・減量・患者教育", "早期の人工関節置換術", "オピオイドの定期内服", "全例での関節内ステロイド反復注射"],
    correct: 0,
    explanation: "【要点】膝・股関節OAの中核治療は運動療法・減量・患者教育で、薬物や手術に優先する(Lancet)。\n【背景/エビデンス】OAはプライマリ・ケアで最も多く扱う問題の一つ。筋力強化・有酸素運動が疼痛と機能を改善し、過体重例では減量が有効。薬物は補助で、NSAIDsは局所を優先し全身投与は最少期間にとどめる。\n【臨床応用】まず運動・減量・教育を継続的に支援し、必要に応じ短期の鎮痛を併用。人工関節置換は保存療法が無効で生活が障害される進行例の選択肢。\n【誤答】早期の一律手術・オピオイド定期内服・ステロイド反復注射は、いずれも第一選択ではなく害が上回りうる。",
    source: { title: "Osteoarthritis: a Lancet Commission", url: "https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(20)32230-3/fulltext" },
    tags: ["変形性関節症", "運動療法", "減量", "整形"]
  },
  {
    id: "rv-hypothyroid-01",
    category: "review",
    difficulty: 1,
    added: "2026-07-16",
    question: "顕性甲状腺機能低下症の診断・治療に関する記述として正しいものはどれか。",
    options: ["TSH低値+fT4高値で診断する", "無症状の成人全員に対しTSHスクリーニングが強く推奨される", "治療の第一選択は乾燥甲状腺末(T3含有製剤)である", "TSH高値+fT4低値で診断し、レボチロキシンで補充する"],
    correct: 3,
    explanation: "【要点】顕性甲状腺機能低下症はTSH高値+fT4低値で診断し、レボチロキシン(LT4)単剤で補充するのが標準(Lancet)。\n【背景/エビデンス】原因は橋本病が多い。LT4は半減期が長く1日1回・空腹時服用が基本。開始量は年齢・心疾患・重症度で調整し、TSHを目安に6〜8週ごとに用量を漸増する。\n【臨床応用】過少・過剰補充はいずれも心血管・代謝リスクとなるため、TSHを目標域に保つ。無症候の一般成人へのルーチンTSHスクリーニングはUSPSTFで根拠不十分とされる。\n【誤答】『TSH低値+fT4高値』は機能亢進の所見で誤り。T3含有製剤は第一選択でなく、全員スクリーニングも推奨されない。",
    source: { title: "Hypothyroidism (Lancet Seminar 2024)", url: "https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(24)01614-3/abstract" },
    tags: ["甲状腺", "甲状腺機能低下症", "レボチロキシン", "内分泌"]
  },
  {
    id: "rv-lbp-01",
    category: "review",
    difficulty: 2,
    added: "2026-07-16",
    question: "警告徴候(red flags)のない急性・亜急性の非特異的腰痛の初期対応として、Lancetのレビュー等が支持する方針はどれか。",
    options: ["全例で早期に腰椎MRI/CTを撮影する", "画像は原則不要で、患者教育・活動維持・必要時の対症療法を行う", "早期からオピオイドを定期処方する", "安静臥床を長期に指示する"],
    correct: 1,
    explanation: "【要点】red flagsのない非特異的腰痛では、ルーチンの画像は不要で、安心の付与・患者教育・活動維持を軸に管理する(Lancet)。\n【背景/エビデンス】重篤な基礎疾患を示唆する所見がなければ、早期の腰椎画像は転帰を改善せず、過剰診断・過剰治療につながる。画像・オピオイド・手術の過剰使用が世界的な課題とされる。\n【臨床応用】活動性の維持を促し、必要時にNSAIDs等を短期併用する。腫瘍・感染・馬尾症候群・骨折を示唆するred flagsがあれば速やかに精査する。\n【誤答】全例の早期画像・オピオイド定期処方・長期の安静臥床は、いずれも推奨されず害が上回る。",
    source: { title: "Non-specific low back pain (The Lancet)", url: "https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(16)30970-9/abstract" },
    tags: ["腰痛", "画像検査", "整形", "外来"]
  },
  {
    id: "rv-ida-01",
    category: "review",
    difficulty: 2,
    added: "2026-07-16",
    question: "鉄欠乏性貧血(IDA)の治療に関する近年のレビューの考え方として適切なものはどれか。",
    options: ["経口鉄は毎日2〜3回に分けて連日投与するのが最も効率的である", "静注鉄は真のアレルギーの頻度が高く原則禁忌である", "経口鉄は隔日・単回投与でも吸収効率がよく、不耐や吸収不良・活動性炎症では静注鉄を考慮する", "原因検索は不要で鉄補充のみ行えばよい"],
    correct: 2,
    explanation: "【要点】経口鉄は隔日・1日1回投与でヘプシジンの変動を避け吸収効率がよいとされ、不耐・吸収不良・活動性炎症では静注鉄を考慮する。\n【背景/エビデンス】従来の分割高用量はヘプシジン上昇で吸収を頭打ちにし副作用も増やす。静注鉄は1〜2回で鉄欠を補える製剤が好まれ、真のアレルギーはまれ(多くは補体活性化関連の擬似アレルギー)。\n【臨床応用】必ず鉄欠乏の原因(消化管出血・月経過多・吸収不良等)を検索する。とくに中高年の原因不明IDAは消化管精査を要する。\n【誤答】連日分割が最効率・静注鉄が原則禁忌・原因検索不要は、いずれも誤り。",
    source: { title: "Management of iron deficiency: evidence-based and expert consensus recommendations (Lancet Haematology 2025)", url: "https://www.thelancet.com/journals/lanhae/article/PIIS2352-3026(25)00038-9/abstract" },
    tags: ["貧血", "鉄欠乏", "静注鉄", "血液"]
  },
  {
    id: "rv-asthma-01",
    category: "review",
    difficulty: 2,
    added: "2026-07-16",
    question: "成人喘息の管理に関する近年の考え方(Annals In the Clinic等)として適切なものはどれか。",
    options: ["軽症でもICSを含む治療を基本とし、SABA単独に頼らない", "発作時のSABA単独使用のみで長期管理する", "全例で経口ステロイドを維持投与する", "吸入ステロイドは重症例にのみ使用する"],
    correct: 0,
    explanation: "【要点】現在の喘息管理は、軽症でもICS(吸入ステロイド)を含む治療を基盤とし、SABA単独への依存を避ける方向にある。\n【背景/エビデンス】SABA単独は症状を一時緩和するが基礎の気道炎症を治療せず、過剰使用は増悪・死亡リスクと関連する。ICS/ホルモテロールを必要時または定期で用いる戦略(GINA)が普及している。\n【臨床応用】吸入手技とアドヒアランス、増悪歴・コントロール状態を評価してステップアップ/ダウンを行う。誘因・併存症(鼻炎・肥満・GERD)も併せて管理する。\n【誤答】SABA単独での長期管理・経口ステロイド維持・ICSを重症のみは、いずれも現行の推奨に反する。",
    source: { title: "Care of the Patient With Asthma (Annals of Internal Medicine, In the Clinic)", url: "https://www.acpjournals.org/doi/10.7326/ANNALS-25-01034" },
    tags: ["喘息", "ICS", "呼吸器", "外来"]
  },
  {
    id: "rv-ckd-01",
    category: "review",
    difficulty: 2,
    added: "2026-07-16",
    question: "慢性腎臓病(CKD)のプライマリ・ケアでの管理として、JAMAレビュー等が挙げる中核要素はどれか。",
    options: ["蛋白制限のみで薬物は使わない", "腎機能にかかわらず全例を直ちに透析導入する", "血圧やアルブミン尿は放置してよい", "心血管リスク低減、アルブミン尿へのRAS阻害薬、腎毒性物質の回避、合併症モニタリング"],
    correct: 3,
    explanation: "【要点】CKD管理の中核は、心血管リスク低減(スタチン・血圧管理)、アルブミン尿へのACE阻害薬/ARB、腎毒性物質の回避、合併症(高K・貧血等)のモニタリングである(JAMA 2019レビュー)。\n【背景/エビデンス】CKDはGFR<60または尿アルブミン≥30mg/日が3か月以上持続する状態で、世界人口の8〜16%が該当。先進国では糖尿病・高血圧が主因。\n【臨床応用】近年はSGLT2阻害薬が糖尿病の有無を問わず腎保護に加わる。eGFR<30、高度アルブミン尿、急速なeGFR低下は腎臓専門医へ紹介する。\n【誤答】蛋白制限のみ・一律の即透析・血圧/蛋白尿の放置は、いずれも不適切である。",
    source: { title: "Chronic Kidney Disease Diagnosis and Management: A Review (JAMA 2019)", url: "https://jamanetwork.com/journals/jama/fullarticle/2752067" },
    tags: ["CKD", "腎臓", "アルブミン尿", "外来"]
  },
  {
    id: "rv-rhinitis-01",
    category: "review",
    difficulty: 1,
    added: "2026-07-16",
    question: "生活の質に影響する持続性のアレルギー性鼻炎に対する第一選択薬として、AAFPのレビュー等が支持するのはどれか。",
    options: ["経口第一世代抗ヒスタミン薬", "鼻噴霧ステロイド(intranasal corticosteroid)", "経口ステロイドの連日内服", "経口充血除去薬の長期使用"],
    correct: 1,
    explanation: "【要点】QOLに影響する持続性アレルギー性鼻炎の第一選択は鼻噴霧ステロイド(INCS)で、抗ヒスタミン薬より症状改善に優れる(AAFP)。\n【背景/エビデンス】INCSは鼻閉を含む鼻症状全般に有効で、必要時使用でも効果がある。追加が必要な場合は鼻噴霧抗ヒスタミンとの併用が最も効果的とされる。\n【臨床応用】正しい噴霧手技を指導し、季節性では症状期の前から開始すると有効。第一世代抗ヒスタミンは鎮静・抗コリン作用のため高齢者等では避ける。\n【誤答】経口第一世代抗ヒスタミンは第一選択でなく、経口ステロイド連日や経口充血除去薬の長期使用は有害/不適切。",
    source: { title: "Allergic Rhinitis: Rapid Evidence Review (AAFP 2023)", url: "https://www.aafp.org/pubs/afp/issues/2023/0500/allergic-rhinitis.html" },
    tags: ["アレルギー性鼻炎", "鼻噴霧ステロイド", "耳鼻科", "外来"]
  },
  {
    id: "rv-obesity-02",
    category: "review",
    difficulty: 2,
    added: "2026-07-16",
    question: "プライマリ・ケアでの肥満治療に関するレビュー(JAMA Intern Med)の要点として適切なものはどれか。",
    options: ["生活習慣介入は無効なので最初から手術する", "薬物療法は生活習慣介入の代わりに単独で行う", "生活習慣介入を基盤に、必要に応じ薬物療法や手術を組み合わせ、共同意思決定で計画する", "体重は自己責任であり医療的介入は不要"],
    correct: 2,
    explanation: "【要点】肥満治療は生活習慣介入を基盤に、効果・患者希望・実行可能性を踏まえて薬物療法や手術を組み合わせ、共同意思決定で柔軟な計画を立てる(JAMA Intern Med 2024レビュー)。\n【背景/エビデンス】米国成人の40%超が肥満。生活習慣介入は1年で平均2〜9%の減量を得るが再増加も多い。近年はGLP-1/GIP系など高効果の抗肥満薬が登場し選択肢が拡大している。\n【臨床応用】BMIや合併症を評価し、5%以上の減量で代謝指標が改善する。減量薬は中止で再増加しうるため継続戦略と有害事象管理が要る。\n【誤答】最初から一律手術・薬物単独・『介入不要』は、いずれも適切でない。",
    source: { title: "Approach to Obesity Treatment in Primary Care: A Review (JAMA Internal Medicine 2024)", url: "https://jamanetwork.com/journals/jamainternalmedicine/fullarticle/2816061" },
    tags: ["肥満", "生活習慣", "抗肥満薬", "外来"]
  },
  {
    id: "cl-multi-sickday-01",
    category: "clinical",
    difficulty: 2,
    added: "2026-07-16",
    question: "発熱と下痢による脱水で急性腎障害(AKI)をきたした2型糖尿病患者。急性期に『シックデイ』として一時中止を検討すべき薬剤を選べ。",
    options: ["SGLT2阻害薬", "NSAIDs", "アトルバスタチン(スタチン)", "ACE阻害薬(またはARB)"],
    correct: [0, 1, 3],
    explanation: "【要点】脱水+AKIの急性期は、腎血流や代謝に影響する薬剤(ACE阻害薬/ARB、NSAIDs、SGLT2阻害薬、メトホルミン、利尿薬など)を一時中止する(sick day rules)。\n【なぜか】ACE阻害薬/ARBとNSAIDsは腎自動調節を障害しAKIを悪化させる。SGLT2阻害薬は脱水下で正常血糖ケトアシドーシスのリスクがあり休薬が望ましい。\n【臨床応用】あくまで急性期の一時休薬で、回復後に適応を再評価して再開する。患者へのシックデイ指導が再発予防に有用。\n【誤答】スタチンは急性期に中止する必要はなく、シックデイ休薬の対象ではない(横紋筋融解などの特別な状況を除く)。",
    source: { title: "Update in Outpatient General Internal Medicine (Am J Med)", url: "https://www.amjmed.com/article/S0002-9343(26)00149-X/abstract?rss=yes" },
    tags: ["AKI", "sick day rules", "SGLT2阻害薬", "複数選択"]
  },
  {
    id: "cl-multi-asb-01",
    category: "clinical",
    difficulty: 2,
    added: "2026-07-16",
    question: "IDSA 2019ガイドラインに基づき、無症候性細菌尿に対して抗菌薬治療(スクリーニング含む)が推奨される状況を選べ。",
    options: ["粘膜出血を伴う侵襲的な泌尿器処置の前", "血糖コントロール良好で無症状の糖尿病患者", "妊婦", "尿カテーテル留置中で無症状の高齢者"],
    correct: [0, 2],
    explanation: "【要点】IDSA 2019は、無症候性細菌尿のスクリーニング・治療を推奨するのは妊婦と、侵襲的泌尿器処置(粘膜出血を伴う)の前に限るとした。\n【理由】妊娠では腎盂腎炎・早産リスク低減、泌尿器処置前では菌血症予防の便益が示されている。それ以外(高齢者、施設入所、糖尿病、カテーテル留置)は、症状がなければ治療しても予後を改善せず、耐性菌やC. difficile感染のリスクを増やす。\n【臨床応用】高齢者の非特異的症状+尿培養陽性だけで安易に治療しないことが抗菌薬適正使用の要点。\n【誤答】カテーテル留置中の無症状例、無症状の糖尿病例は治療対象ではない。",
    source: { title: "IDSA 2019 Clinical Practice Guideline for the Management of Asymptomatic Bacteriuria (Clin Infect Dis)", url: "https://academic.oup.com/cid/article/68/10/e83/5407612" },
    tags: ["感染症", "無症候性細菌尿", "抗菌薬適正使用", "複数選択"]
  },
  {
    id: "rv-multi-organprotect-01",
    category: "review",
    difficulty: 2,
    added: "2026-07-16",
    question: "2型糖尿病+心血管/腎の高リスク患者において、血糖降下作用とは独立に臓器保護のエビデンスを持つ薬剤クラスを選べ。",
    options: ["GLP-1受容体作動薬", "スルホニル尿素(SU)薬", "DPP-4阻害薬", "SGLT2阻害薬"],
    correct: [0, 3],
    explanation: "【要点】臓器保護(心血管・腎)の一次エビデンスを持つのはSGLT2阻害薬とGLP-1受容体作動薬。\n【エビデンス】SGLT2阻害薬は心不全入院とCKD進行の抑制に強く(EMPA-REG、DAPA-HF、EMPA-KIDNEY等)、GLP-1受容体作動薬はASCVDイベント抑制と体重減少に優れる(LEADER、SELECT等)。両者は作用機序が異なり併用も可能。\n【臨床応用】HbA1cとは独立に、守りたい臓器(心不全・CKDならSGLT2阻害薬、ASCVD・肥満ならGLP-1RA)で第2剤を選ぶ。\n【誤答】SU薬・DPP-4阻害薬は血糖は下げるが、心血管・腎アウトカムの改善を示すエビデンスは確立していない(DPP-4阻害薬は概ね中立)。",
    source: { title: "CVOT summit report 2024 (PMC)", url: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC12048985/" },
    tags: ["糖尿病", "SGLT2阻害薬", "GLP-1", "臓器保護", "複数選択"]
  },
  {
    id: "rv-multi-sglt2-01",
    category: "review",
    difficulty: 3,
    added: "2026-07-16",
    question: "SGLT2阻害薬に関する記述のうち、現在のエビデンスに照らして正しいものを選べ。",
    options: ["重症の低血糖を高頻度に引き起こすため単独では使いにくい", "糖尿病の有無にかかわらずCKD進行を抑制する", "投与初期のeGFR低下(initial dip)は多くが可逆性で継続してよい", "LVEFを問わず心不全入院を抑制する"],
    correct: [1, 2, 3],
    explanation: "【要点】SGLT2阻害薬はCKD進行抑制(糖尿病の有無を問わず)、全LVEFでの心不全入院抑制、可逆性のinitial dipという特徴を持つ。\n【エビデンス】EMPA-KIDNEY/DAPA-CKDは非糖尿病CKDでも腎保護を示し、EMPEROR-Preserved/DELIVERはHFpEFを含む全LVEFで心不全入院を抑制。導入初期のeGFR低下は血行動態性で多くは可逆性、継続が推奨される。\n【注意】性器感染症、脱水、まれに正常血糖ケトアシドーシスに留意する。\n【誤答】インスリン分泌に依存しない機序のため単独では低血糖はまれで、『重症低血糖を高頻度に起こす』は誤り。",
    source: { title: "Empagliflozin in Patients with Chronic Kidney Disease (EMPA-KIDNEY, NEJM 2023)", url: "https://www.nejm.org/doi/full/10.1056/NEJMoa2204233" },
    tags: ["SGLT2阻害薬", "CKD", "心不全", "複数選択"]
  },
  {
    id: "jr-surmount5-01",
    category: "journal",
    difficulty: 2,
    added: "2026-07-16",
    question: "肥満(2型糖尿病なし)の成人を対象に、チルゼパチドとセマグルチドを直接比較したSURMOUNT-5試験(NEJM 2025)の主要な減量効果の結果はどれか。",
    options: ["両薬の減量効果は同等だった", "セマグルチドが有意に大きい減量を示した", "チルゼパチドが有意に大きい減量を示した(約20% vs 約14%)", "いずれも臨床的に意味のある減量を示さなかった"],
    correct: 2,
    explanation: "【要点】SURMOUNT-5は、糖尿病のない肥満成人でチルゼパチド(GIP/GLP-1)がセマグルチドより有意に大きい減量を示した初の直接比較試験。\n【エビデンス】751例を最大耐用量(チルゼパチド10/15mg、セマグルチド1.7/2.4mg)に無作為化し72週。平均体重変化は−20.2% vs −13.7%(約22.8kg vs 15.0kg)、腹囲も−18.4cm vs −13.0cmでチルゼパチドが優越した。消化器有害事象による中止はセマグルチド5.6% vs チルゼパチド2.7%。\n【臨床応用】減量幅を重視する場面ではチルゼパチドが選択肢だが、費用・供給・忍容性・アウトカムの蓄積度も踏まえ個別化する。\n【誤答】同等・セマグルチド優越・臨床的無効は、いずれも試験結果と異なる。",
    source: { title: "Tirzepatide as Compared with Semaglutide for the Treatment of Obesity (SURMOUNT-5, NEJM 2025)", url: "https://www.nejm.org/doi/full/10.1056/NEJMoa2416394" },
    tags: ["肥満", "チルゼパチド", "セマグルチド", "インクレチン"]
  },
  {
    id: "jr-select-01",
    category: "journal",
    difficulty: 2,
    added: "2026-07-16",
    question: "心血管疾患の既往があり2型糖尿病のない過体重・肥満の成人を対象としたSELECT試験で、セマグルチド2.4mgが示した主要心血管アウトカムの結果はどれか。",
    options: ["主要心血管イベントに有意差はなかった", "主要心血管イベント(MACE)を約20%低下させた", "全死亡はむしろ増加した", "体重は減ったが心血管イベントは増えた"],
    correct: 1,
    explanation: "【要点】SELECTは、糖尿病のない心血管疾患既往+過体重/肥満の患者で、セマグルチド2.4mgがMACEを有意に低下させた初のエビデンス。\n【エビデンス】17,604例を標準治療への上乗せで無作為化。心血管死/非致死性MI/非致死性脳卒中の複合は6.5% vs 8.0%(HR 0.80)で約20%減。平均体重変化は−9.4% vs −0.9%だった。\n【臨床応用】肥満は独立した心血管リスクとして治療対象になり、糖尿病がなくても高リスク例でGLP-1受容体作動薬が二次予防の選択肢となりうる。消化器症状に留意し用量を漸増する。\n【誤答】有意差なし・全死亡増加・イベント増加は、いずれも試験結果と逆である。",
    source: { title: "Semaglutide and Cardiovascular Outcomes in Obesity without Diabetes (SELECT, NEJM 2023)", url: "https://www.nejm.org/doi/full/10.1056/NEJMoa2307563" },
    tags: ["肥満", "セマグルチド", "GLP-1", "心血管二次予防"]
  },
  {
    id: "gl-osteo-screen-01",
    category: "guideline",
    difficulty: 1,
    added: "2026-07-16",
    question: "2025年のUSPSTFによる骨粗鬆症スクリーニング勧告(骨折予防)として正しいものはどれか。",
    options: ["全成人に一律で骨密度測定を行う", "スクリーニングは推奨しない", "男性への骨密度スクリーニングを強く推奨する", "65歳以上の女性、および骨折リスクの高い65歳未満の閉経後女性にスクリーニングを推奨(いずれもGrade B)"],
    correct: 3,
    explanation: "【要点】2025年USPSTFは、65歳以上の女性と、臨床的リスク評価で骨折リスクが高い65歳未満の閉経後女性に、骨粗鬆症スクリーニング(DXA等)を推奨した(いずれもGrade B)。\n【背景】対象は脆弱性骨折の既往や骨を弱める疾患のない集団。若年閉経後女性のリスク評価にはFRAX等のツールを用いる。\n【臨床応用】結果に応じて生活指導・転倒予防・必要時の薬物治療につなげる。骨折既往のある例は評価対象外で、直ちに治療を検討する。\n【誤答】全成人一律・スクリーニング非推奨は誤り。男性のスクリーニングは現時点で証拠不十分(I statement)であり『強く推奨』は当たらない。",
    source: { title: "Screening for Osteoporosis to Prevent Fractures: USPSTF Recommendation Statement (JAMA 2025)", url: "https://jamanetwork.com/journals/jama/fullarticle/2829238" },
    tags: ["骨粗鬆症", "スクリーニング", "USPSTF", "予防"]
  },
  {
    id: "gl-osteo-tx-01",
    category: "guideline",
    difficulty: 2,
    added: "2026-07-16",
    question: "米国内科学会(ACP)の骨粗鬆症薬物治療ガイドライン(Annals)で、原発性骨粗鬆症の初回治療の第一選択とされる薬剤クラスはどれか。",
    options: ["ビスホスホネート(アレンドロン酸・リセドロン酸・ゾレドロン酸)", "副甲状腺ホルモン関連薬(テリパラチド)を全例で第一選択", "選択的エストロゲン受容体モジュレーター(SERM)", "カルシトニン"],
    correct: 0,
    explanation: "【要点】ACPガイドラインは、原発性骨粗鬆症の初回薬物治療の第一選択としてビスホスホネート(アレンドロン酸・リセドロン酸・ゾレドロン酸)を推奨する(女性で強い推奨・高確実性)。\n【エビデンス】骨折抑制効果・安全性・費用対効果のバランスに基づく。ビスホスホネートに不耐/禁忌の例ではデノスマブを第二選択とする。骨折リスクが非常に高い例ではロモソズマブやテリパラチド等の骨形成薬を考慮する。\n【臨床応用】カルシウム・ビタミンDの充足を基盤に、消化管・腎機能・歯科状態を確認して開始する。\n【誤答】テリパラチドの全例第一選択は不適切で、SERM・カルシトニンは骨折抑制/安全性の点で初回第一選択には位置づけられない。",
    source: { title: "ACP Recommends Bisphosphonates for Initial Treatment of Primary Osteoporosis (Annals/ACP)", url: "https://www.acponline.org/acp-newsroom/american-college-of-physicians-recommends-bisphosphonates-for-initial-treatment-for-osteoporosis-in" },
    tags: ["骨粗鬆症", "ビスホスホネート", "ACP", "骨折予防"]
  },
  {
    id: "cl-osteo-01",
    category: "clinical",
    difficulty: 2,
    added: "2026-07-16",
    question: "72歳女性、脆弱性骨折の既往はないが大腿骨近位部のTスコア −2.7。腎機能正常、消化管疾患なし。近年のガイドラインに沿った初期方針として最も適切なものはどれか。",
    options: ["薬物治療は不要で経過観察のみ", "まずカルシトニン点鼻を開始する", "カルシウム・ビタミンDの充足と生活・転倒対策を基盤に、第一選択としてビスホスホネートを開始", "直ちにデノスマブを第一選択で開始し中止時期は考慮しない"],
    correct: 2,
    explanation: "【要点】Tスコア≤−2.5で骨粗鬆症と診断され、禁忌がなければビスホスホネートを第一選択に、カルシウム・ビタミンD充足と転倒予防を基盤として開始する。\n【背景/エビデンス】ACPはビスホスホネートを初回第一選択(女性で強い推奨)とし、不耐/禁忌でデノスマブを第二選択とする。デノスマブは中止すると急速な骨密度低下・多発椎体骨折のリスクがあり、中止時は他剤へ移行する必要がある。\n【臨床応用】腎機能・歯科・消化管を確認し、経口不耐や服薬困難ではゾレドロン酸静注も選択肢。定期的に治療効果と継続を再評価する。\n【誤答】経過観察のみは骨折リスクを放置し不適切。カルシトニンは第一選択でなく、デノスマブの中止時期を考慮しない運用は反跳性骨折の点で危険。",
    source: { title: "ACP Recommends Bisphosphonates for Initial Treatment of Primary Osteoporosis (Annals/ACP)", url: "https://www.acponline.org/acp-newsroom/american-college-of-physicians-recommends-bisphosphonates-for-initial-treatment-for-osteoporosis-in" },
    tags: ["骨粗鬆症", "ビスホスホネート", "デノスマブ", "外来"]
  },
  {
    id: "rv-multi-osteo-01",
    category: "review",
    difficulty: 2,
    added: "2026-07-16",
    question: "骨粗鬆症の治療・管理について、現在の一般的なエビデンス・推奨に照らして正しいものを選べ。",
    options: ["カルシウム・ビタミンDの充足を治療の基盤とする", "閉経後女性の初回薬物治療の第一選択はビスホスホネートである", "デノスマブは中止すると急速な骨密度低下・多発椎体骨折のリスクがあり、中止・切替時に注意する", "経口ビスホスホネートによる顎骨壊死は高頻度で、骨粗鬆症治療では使用を避けるべきである"],
    correct: [0, 1, 2],
    explanation: "【要点】骨粗鬆症治療の要点は、ビスホスホネートを第一選択とすること、デノスマブ中止時の反跳性骨折に注意すること、カルシウム・ビタミンD充足を基盤とすることである。\n【エビデンス】ACPはビスホスホネート(アレンドロン酸等)を初回第一選択とし、不耐/禁忌でデノスマブを次善とする。デノスマブは中止で骨吸収が反跳し多発椎体骨折の報告があるため、中止時は他の抗骨吸収薬へ移行する。\n【臨床応用】十分なカルシウム・ビタミンD、運動・転倒予防を土台に薬物治療を行い、定期的に再評価する。\n【誤答】経口ビスホスホネートに関連した顎骨壊死は骨粗鬆症用量ではまれ(主に高用量静注のがん領域で問題)であり、『高頻度・使用回避』は誤りである。",
    source: { title: "ACP Updates Clinical Recommendations on Treatment of Osteoporosis (AAFP)", url: "https://www.aafp.org/pubs/afp/afp-community-blog/entry/acp-updates-clinical-recommendations-on-treatment-of-osteoporosis.html" },
    tags: ["骨粗鬆症", "ビスホスホネート", "デノスマブ", "複数選択"]
  },
  {
    id: "jr-bproad-01",
    category: "journal",
    difficulty: 2,
    added: "2026-07-17",
    question: "2型糖尿病+心血管リスク因子を持つ患者で、収縮期血圧の目標を<120 mmHg(強化)と<140 mmHg(標準)で比較したBPROAD試験の主要結果はどれか。",
    options: ["主要心血管複合アウトカムに有意差はなかった", "強化療法群で主要心血管複合アウトカムが有意に低下した(約21%減)", "強化療法群で心血管イベントがむしろ増加した", "強化療法群で全死亡が有意に増加し試験が中止された"],
    correct: 1,
    explanation: "【要点】BPROADで、SBP<120 mmHgを目指す強化降圧は<140 mmHgの標準より主要心血管複合を有意に低下させた(約21%減)。\n【背景/エビデンス】中国の2型糖尿病+CVDリスク因子を持つ12,821例、中央値4.2年。非致死性脳卒中/非致死性MI/心不全の治療・入院/心血管死の複合が1.65 vs 2.09/100人年(HR 0.79)。ただし症候性低血圧・高カリウム血症は強化群で多かった。\n【臨床応用】糖尿病でもより低いSBP目標の便益を支持する。一方で低血圧・電解質・腎機能をモニタリングし、忍容性と個別リスクに応じて目標を調整する。\n【誤答】有意差なし・イベント増加・全死亡増加で中止は、いずれも試験結果と異なる。",
    source: { title: "BPROAD: Intensive Blood-Pressure Control in Patients with Type 2 Diabetes (ACC/AHA 2024)", url: "https://www.acc.org/latest-in-cardiology/articles/2024/11/13/21/17/sat-942am-bproad-aha-2024" },
    tags: ["高血圧", "糖尿病", "降圧目標", "BPROAD"]
  },
  {
    id: "jr-semaaud-01",
    category: "journal",
    difficulty: 2,
    added: "2026-07-17",
    question: "アルコール使用障害と肥満を併存する患者を対象に、週1回セマグルチドをプラセボと比較した無作為化試験(Lancet)で示唆された方向性はどれか。",
    options: ["飲酒量・関連アウトカムに影響はなかった", "むしろ飲酒量が増加した", "飲酒量の減少などアルコール関連アウトカムの改善が示唆された", "重篤な肝障害が多発し試験が中止された"],
    correct: 2,
    explanation: "【要点】アルコール使用障害+肥満の患者で、週1回セマグルチドは飲酒関連アウトカム(飲酒量・重飲酒日の減少等)の改善を示唆した。\n【背景/エビデンス】GLP-1受容体作動薬は中脳報酬系への作用を介して飲酒欲求を抑える可能性が指摘され、先行の小規模RCTやこのLancet試験で飲酒量の減少が報告された。ただし規模は限定的で効果量の解釈には注意を要し、確立した適応ではなく追試が必要。\n【臨床応用】肥満や2型糖尿病を併存するAUD患者で将来的な選択肢となりうるが、現時点で標準治療(心理社会的支援、ナルトレキソン/アカンプロサート等)を置き換えるものではない。\n【誤答】影響なし・飲酒増加・肝障害多発で中止は、示された方向と異なる。",
    source: { title: "Once-weekly semaglutide versus placebo in patients with alcohol use disorder and comorbid obesity (Lancet 2026)", url: "https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(26)00305-3/fulltext" },
    tags: ["アルコール使用障害", "セマグルチド", "GLP-1", "依存症"]
  },
  {
    id: "jr-soul-01",
    category: "journal",
    difficulty: 2,
    added: "2026-07-17",
    question: "既知のASCVDまたはCKDを伴う2型糖尿病の高リスク成人で、経口セマグルチド(最大14mg)をプラセボと比較したSOUL試験の主要心血管アウトカムはどれか。",
    options: ["主要心血管イベント(MACE)を有意に約14%低下させた", "MACEに有意差はなかった", "MACEをむしろ増加させた", "全死亡を半減させた"],
    correct: 0,
    explanation: "【要点】SOULで、経口セマグルチドはMACE(心血管死/非致死性MI/非致死性脳卒中)を有意に約14%低下させた。\n【背景/エビデンス】50歳以上でASCVD/CKDを持つ2型糖尿病9,650例、平均約4年。主要イベントは12.0% vs 13.8%(HR 0.86、p=0.006)。経口GLP-1受容体作動薬として初めて心血管ベネフィットを示し、効果はSGLT2阻害薬併用の有無で概ね一貫していた。\n【臨床応用】注射が難しい患者でも経口GLP-1で心血管保護を狙える。消化器症状に留意し、起床時・空腹時に少量の水で服用し30分空けるなど吸収条件の指導が必要。\n【誤答】有意差なし・増加・全死亡半減は、いずれも試験結果と異なる。",
    source: { title: "Oral Semaglutide and Cardiovascular Outcomes in High-Risk Type 2 Diabetes (SOUL, NEJM 2025)", url: "https://www.acc.org/latest-in-cardiology/clinical-trials/2025/03/27/15/04/soul" },
    tags: ["糖尿病", "経口セマグルチド", "GLP-1", "心血管アウトカム"]
  },
  {
    id: "gl-glp1periop-01",
    category: "guideline",
    difficulty: 2,
    added: "2026-07-17",
    question: "GLP-1受容体作動薬を使用中の患者の待機的手術・内視鏡前の周術期管理について、2024年の多学会(ASA等)アップデートの考え方はどれか。",
    options: ["全例で1週間以上休薬しなければ手術できない", "GLP-1使用者には一律に全身麻酔を禁忌とする", "絶食は不要で通常どおり摂取してよい", "消化管症状がなく高リスクでなければ継続も許容され、当日は固形物を24時間絶食とするなど個別化する"],
    correct: 3,
    explanation: "【要点】2024年の多学会アップデートは、GLP-1受容体作動薬の一律休薬から、リスクに応じた個別化へ方針を転換した。\n【背景/エビデンス】GLP-1RAは胃排出を遅らせ、麻酔・鎮静下の誤嚥リスクが懸念される。ただし胃内残留は増えるものの実際の肺誤嚥率は低い(概ね0.1〜0.2%)。高リスク(用量漸増期・高用量・週1回製剤・消化器症状あり)以外では継続も許容し、固形物24時間絶食(清澄水は可)などで対応する。\n【臨床応用】症状と投与状況を評価し、必要に応じ胃内容の超音波評価や絶食延長を検討する。最終判断は施設の麻酔科方針と個別状況による。\n【誤答】一律1週間休薬必須・全身麻酔一律禁忌・絶食不要は、いずれも現行の個別化アプローチに反する。",
    source: { title: "Perioperative Management of GLP-1 Receptor Agonists: Balancing Aspiration Risk with Therapeutic Benefit", url: "https://link.springer.com/article/10.1007/s42399-025-02079-9" },
    tags: ["GLP-1", "周術期", "誤嚥", "麻酔"]
  },
  {
    id: "rv-admab-01",
    category: "review",
    difficulty: 2,
    added: "2026-07-17",
    question: "早期アルツハイマー病(軽度認知障害〜軽度認知症)に対する抗アミロイドβ抗体(レカネマブ・ドナネマブ)に関する現在の理解として適切なものはどれか。",
    options: ["認知機能低下を統計的に緩やかにするが臨床的意義には議論があり、ARIA等の安全性管理を要する", "認知症を治癒させることが確立している", "有効性は全く示されていない", "副作用がなく安全性上の懸念はない"],
    correct: 0,
    explanation: "【要点】レカネマブ・ドナネマブは早期ADで認知・機能低下を統計的に緩やかにするが、効果量の臨床的意義には議論があり、ARIA(アミロイド関連画像異常)などの安全管理が必須である。\n【背景/エビデンス】第3相(CLARITY-AD、TRAILBLAZER-ALZ 2)でCDR-SB等の悪化を有意に抑制した。投与前にアミロイドPET/CSFでの病理確認、APOE4遺伝型による脳出血・浮腫(ARIA-H/E)リスク評価、定期MRIによるモニタリングが求められる。\n【臨床応用】適応はMCI〜軽度ADに限られ、抗凝固併用や特定の状況では慎重を要し、専門施設での投与・監視が前提となる。\n【誤答】治癒が確立・有効性皆無・安全性懸念なしは、いずれも現状のエビデンスと異なる。",
    source: { title: "Balancing benefit and risk in early Alzheimer's disease: the EMA assessment of lecanemab and donanemab (PMC)", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12995497/" },
    tags: ["認知症", "アルツハイマー病", "抗アミロイド抗体", "神経"]
  },
  {
    id: "cl-bempedoic-01",
    category: "clinical",
    difficulty: 2,
    added: "2026-07-17",
    question: "スタチン不耐の高リスク患者を対象としたCLEAR Outcomes試験(ベンペド酸 vs プラセボ)に関する記述のうち、正しいものを選べ。",
    options: ["筋症状(筋痛)がプラセボより著明に増加した", "ベンペド酸はATPクエン酸リアーゼ阻害薬で、コレステロール合成をスタチンの上流で抑える", "尿酸値の上昇や痛風・胆石の増加が報告された", "主要心血管イベント(MACE)を有意に低下させた"],
    correct: [1, 2, 3],
    explanation: "【要点】CLEAR Outcomesで、スタチン不耐患者へのベンペド酸はMACEを有意に低下させ、機序はATPクエン酸リアーゼ阻害、代表的有害事象として尿酸上昇・痛風・胆石が増えた。\n【背景/エビデンス】約13,970例(一次+二次予防、スタチン不耐)を対象。4項目MACEを13%、心筋梗塞23%、冠血行再建19%低下させ、一次予防コホートでも有益(HR 0.70)。ベンペド酸は肝で活性化しコレステロール合成をスタチンの上流(ACL)で抑制するため骨格筋への影響が少ない。\n【臨床応用】スタチン不耐でLDL目標未達の例の選択肢。尿酸・痛風既往に留意しモニタリングする。\n【誤答】筋痛はむしろ数値上プラセボより少なく、『著明に増加』は誤りである。",
    source: { title: "CLEAR Outcomes: Bempedoic Acid in Statin-Intolerant Patients (ACC 2023 / NEJM)", url: "https://www.acc.org/Latest-in-Cardiology/Articles/2023/03/01/22/45/Sat-930am-clear-outcomes-acc-2023" },
    tags: ["脂質", "ベンペド酸", "スタチン不耐", "複数選択"]
  },
  {
    id: "gl-brca-01",
    category: "guideline",
    difficulty: 1,
    added: "2026-07-18",
    question: "2024年のUSPSTFによる平均リスク女性への乳癌スクリーニング勧告として正しいものはどれか。",
    options: ["50〜74歳の女性に毎年マンモグラフィを推奨", "40歳以上の全女性に毎年マンモグラフィを推奨", "40〜74歳の女性に2年ごとのマンモグラフィを推奨(Grade B)", "リスクにかかわらず75歳以上にも毎年推奨"],
    correct: 2,
    explanation: "【要点】2024年USPSTFは、平均リスク女性の乳癌スクリーニング開始年齢を50歳から40歳へ引き下げ、40〜74歳に2年ごとのマンモグラフィを推奨した(Grade B)。\n【背景/エビデンス】40代女性の乳癌罹患増加や黒人女性での高い死亡率を踏まえた変更。2年ごとは毎年より利益/不利益のバランスが良好と判断された。75歳以上は証拠不十分(I statement)。\n【臨床応用】高濃度乳房への追加超音波・MRIの是非は証拠不十分で個別判断。BRCA変異など高リスク者は別枠でより早期・高頻度の管理を行う。\n【誤答】50歳から・毎年・75歳以上への一律推奨は、いずれも現行勧告と異なる。",
    source: { title: "Screening for Breast Cancer: US Preventive Services Task Force Recommendation Statement (JAMA 2024)", url: "https://pubmed.ncbi.nlm.nih.gov/38687503/" },
    tags: ["がん検診", "乳癌", "USPSTF", "予防"]
  },
  {
    id: "jr-east-01",
    category: "journal",
    difficulty: 2,
    added: "2026-07-18",
    question: "診断早期(1年以内)で心血管危険因子を持つ心房細動患者を対象に、早期リズムコントロール vs 通常治療を比較したEAST-AFNET 4試験の主要結果はどれか。",
    options: ["両群で主要心血管アウトカムに差はなかった", "早期リズムコントロールが主要心血管複合アウトカムを有意に低下させた", "早期リズムコントロールで脳卒中がむしろ増加した", "通常治療(レートコントロール)が全死亡を有意に低下させた"],
    correct: 1,
    explanation: "【要点】EAST-AFNET 4では、診断早期のAFに対する早期リズムコントロール(抗不整脈薬/アブレーション)が、通常治療より主要心血管複合を有意に低下させた。\n【背景/エビデンス】2,789例(発症1年以内、心血管危険因子あり)、中央値約5年。心血管死/脳卒中/心不全または急性冠症候群による入院の複合が有意に減少(HR約0.79)。抗凝固と併存症管理は両群で継続された。\n【臨床応用】症状の有無を問わず、早期AFではリズムコントロールを早めに検討する根拠となる。抗凝固の適応判断はリズム管理とは独立に継続する。\n【誤答】差なし・脳卒中増加・レートコントロールで死亡低下は、いずれも試験結果と異なる。",
    source: { title: "Early Rhythm-Control Therapy in Patients with Atrial Fibrillation (EAST-AFNET 4, NEJM 2020)", url: "https://www.nejm.org/doi/full/10.1056/NEJMoa2019422" },
    tags: ["心房細動", "リズムコントロール", "早期治療", "循環器"]
  },
  {
    id: "gl-zoster-01",
    category: "guideline",
    difficulty: 1,
    added: "2026-07-18",
    question: "組換え帯状疱疹ワクチン(RZV, Shingrix)に関する米国ACIPの推奨として正しいものはどれか。",
    options: ["免疫正常の50歳以上に加え、免疫不全/免疫抑制の19歳以上にも2回接種を推奨", "60歳以上にのみ1回接種を推奨", "生ワクチンであり免疫不全者には禁忌である", "接種は生涯にわたり毎年必要である"],
    correct: 0,
    explanation: "【要点】ACIPは、免疫正常の50歳以上に加え、疾患や治療で免疫不全/免疫抑制状態の19歳以上にもRZV(Shingrix)2回接種を推奨している。\n【背景/エビデンス】RZVは生ワクチンではなく組換えサブユニット(糖蛋白E+AS01Bアジュバント)ワクチンで、免疫不全者にも使用できる。2017年に≥50歳、2021年10月に免疫不全≥19歳へ適応拡大された。標準は2回接種(通常2〜6か月間隔、免疫不全では1〜2か月間隔も可)。\n【臨床応用】帯状疱疹・帯状疱疹後神経痛の予防に有効。過去に生ワクチン(ZVL)接種歴があってもRZVを接種する。\n【誤答】60歳以上のみ・1回のみ・毎年・生ワクチンで禁忌は、いずれも誤り。",
    source: { title: "Use of Recombinant Zoster Vaccine in Immunocompromised Adults Aged ≥19 Years: ACIP Recommendations 2022 (MMWR)", url: "https://www.cdc.gov/mmwr/volumes/71/wr/mm7103a2.htm" },
    tags: ["ワクチン", "帯状疱疹", "ACIP", "予防接種"]
  },
  {
    id: "gl-statin-prim-01",
    category: "guideline",
    difficulty: 2,
    added: "2026-07-18",
    question: "2022年USPSTFのスタチンによる心血管一次予防の勧告として正しいものはどれか。",
    options: ["既往CVDのない全成人にスタチンを一律推奨", "LDLの絶対値のみで開始を決定する", "76歳以上への新規開始を強く推奨", "40〜75歳で危険因子1つ以上かつ推定10年CVDリスク≥10%の成人にスタチンを推奨(Grade B)"],
    correct: 3,
    explanation: "【要点】2022年USPSTFは、40〜75歳で心血管危険因子を1つ以上持ち、推定10年CVDリスク≥10%の成人にスタチンによる一次予防を推奨した(Grade B)。\n【背景/エビデンス】10年リスク7.5〜<10%の層では、患者と相談のうえ選択的に投与する(Grade C)。一次予防のスタチンは全死亡・CVDイベントを減らし、有害は概ね小さいと評価された。\n【臨床応用】まずリスク計算式でリスクを推定し、生活習慣是正を基盤に共同意思決定で開始を判断する。76歳以上の新規開始は証拠不十分(I statement)。\n【誤答】全成人一律・LDL値のみでの決定・76歳以上への強い推奨は、いずれも勧告と異なる。",
    source: { title: "Statin Use for the Primary Prevention of Cardiovascular Disease in Adults: USPSTF Recommendation Statement (JAMA 2022)", url: "https://jamanetwork.com/journals/jama/fullarticle/2795521" },
    tags: ["脂質", "スタチン", "一次予防", "USPSTF"]
  },
  {
    id: "jr-multi-traverse-01",
    category: "journal",
    difficulty: 3,
    added: "2026-07-18",
    question: "性腺機能低下症で心血管疾患既往またはリスクの高い男性を対象にテストステロン補充 vs プラセボを比較したTRAVERSE試験について、正しいものを選べ。",
    options: ["肺塞栓症・急性腎障害の増加も報告された", "心房細動などの不整脈の発生がプラセボより多かった", "主要心血管イベント(MACE)についてプラセボに非劣性だった", "前立腺癌の発生を有意に増加させた"],
    correct: [0, 1, 2],
    explanation: "【要点】TRAVERSEでは、テストステロン補充はMACEについてプラセボに非劣性だったが、心房細動などの不整脈、肺塞栓症、急性腎障害の増加が報告された。\n【背景/エビデンス】症状のある性腺機能低下+心血管疾患既往/高リスクの男性約5,200例(45〜80歳)を経皮テストステロンゲル vs プラセボに割付。心血管死/非致死性MI/非致死性脳卒中の複合は非劣性を満たした。\n【臨床応用】適応のある性腺機能低下症では心血管安全性への一定の安心材料となるが、不整脈・血栓リスクに留意し、適応外(加齢のみ等)の安易な処方は避ける。\n【誤答】前立腺癌(高悪性度含む)の有意な増加は示されておらず、この記述は誤り。",
    source: { title: "Cardiovascular Safety of Testosterone-Replacement Therapy (TRAVERSE, NEJM 2023)", url: "https://www.nejm.org/doi/full/10.1056/NEJMoa2215025" },
    tags: ["テストステロン", "性腺機能低下症", "心血管安全性", "複数選択"]
  },
  {
    id: "cl-multi-hp-01",
    category: "clinical",
    difficulty: 2,
    added: "2026-07-18",
    question: "2024年ACG H. pylori治療ガイドラインに沿った未治療患者へのアプローチとして、正しいものを選べ。",
    options: ["初回治療の第一選択は最適化ビスマス四剤併用療法(14日間)である", "クラリスロマイシン三剤併用は第一選択の推奨から外された", "ペニシリンアレルギーの有無にかかわらずアモキシシリン含有レジメンを使用してよい", "除菌後は治療完了から4週間以上あけて検査で治癒確認を行う"],
    correct: [0, 1, 3],
    explanation: "【要点】2024年ACGは、未治療H. pyloriの第一選択を最適化ビスマス四剤併用療法(14日間)とし、クラリスロマイシン三剤併用を第一選択から外した。除菌後は治癒確認を行う。\n【背景/エビデンス】クラリスロマイシン・レボフロキサシン耐性の世界的な上昇が背景。治癒確認は尿素呼気試験や便中抗原で、治療完了から4週間以上、かつPPIを1〜2週間休薬して行う。\n【臨床応用】ペニシリンアレルギー例ではアモキシシリンを避け、ビスマス四剤(テトラサイクリン+メトロニダゾール)など非ペニシリンレジメンを選ぶ。\n【誤答】ペニシリンアレルギーの有無を問わずアモキシシリンを使用してよい、は誤り(真のアレルギーでは回避が必要)。",
    source: { title: "Practice Tips From the Updated ACG Helicobacter pylori Treatment Guidelines (Gastroenterol Hepatol 2026)", url: "https://www.gastroenterologyandhepatology.net/archives/february-2026/practice-tips-from-the-updated-helicobacter-pylori-treatment-guidelines/" },
    tags: ["H. pylori", "抗菌薬適正使用", "消化器", "複数選択"]
  },
  {
    id: "rv-insomnia-01",
    category: "review",
    difficulty: 1,
    added: "2026-07-18",
    question: "慢性不眠症(chronic insomnia disorder)の成人に対する初期治療として、ACPガイドライン等が第一に位置づけるのはどれか。",
    options: ["ベンゾジアゼピン系睡眠薬の連日長期投与", "抗ヒスタミン薬の常用", "不眠症に対する認知行動療法(CBT-I)", "アルコールによる入眠導入"],
    correct: 2,
    explanation: "【要点】ACPは、慢性不眠症の成人全例に対し、不眠症に対する認知行動療法(CBT-I)を初期治療とすることを強く推奨する(中等度の質のエビデンス)。\n【背景/エビデンス】CBT-Iは睡眠制限・刺激制御・認知療法・睡眠衛生指導などを組み合わせる非薬物療法で、薬物療法より有害が少なく持続的な効果が期待できる。薬物はCBT-I単独で不十分な場合に、利益・不利益・費用を共有意思決定したうえで短期間に限って併用を検討する。\n【臨床応用】まずCBT-Iへのアクセスを図り(対面/デジタル)、睡眠日誌で経過を評価する。\n【誤答】ベンゾジアゼピンの連日長期・抗ヒスタミン薬の常用・アルコールでの入眠導入は、依存・耐性・睡眠質悪化の点で不適切。",
    source: { title: "Management of Chronic Insomnia Disorder in Adults: A Clinical Practice Guideline From the ACP (Annals of Internal Medicine)", url: "https://www.acpjournals.org/doi/10.7326/M15-2175" },
    tags: ["不眠症", "CBT-I", "睡眠", "外来"]
  },
  {
    id: "gl-lungca-01",
    category: "guideline",
    difficulty: 2,
    added: "2026-07-19",
    question: "喫煙歴のある成人に対する低線量CT(LDCT)を用いた肺癌スクリーニングについて、2021年USPSTF勧告に沿った対象基準はどれか。",
    options: ["55〜74歳・30パックイヤー以上・現喫煙または禁煙後15年以内", "50〜80歳・15パックイヤー以上・現喫煙または禁煙後10年以内", "50〜80歳・20パックイヤー以上・現喫煙または禁煙後15年以内に年1回LDCT", "40歳以上・喫煙歴があれば全員に年1回LDCT"],
    correct: 2,
    explanation: "【要点】2021 USPSTFは、50〜80歳・喫煙20パックイヤー以上で現喫煙または過去15年以内に禁煙した成人に、年1回のLDCT肺癌スクリーニングを推奨(Grade B)。\n【背景/エビデンス】2013年基準(55歳/30パックイヤー)から開始年齢と喫煙量を引き下げ、対象を約1450万人へ拡大。女性・黒人はより少ない喫煙量でも肺癌リスクが高いという格差の是正が狙い。NLST等でLDCTは肺癌死を約20%低下させた。\n【臨床応用】禁煙後15年経過、または根治的肺切除に耐えられない/望まない健康状態になれば中止。禁煙支援と一体で行う。\n【誤答】55歳/30パックイヤーは旧基準、15パックイヤー・40歳開始・喫煙歴のみで全員は現行基準と異なる。",
    source: { title: "Screening for Lung Cancer: US Preventive Services Task Force Recommendation Statement (USPSTF 2021)", url: "https://www.uspreventiveservicestaskforce.org/uspstf/recommendation/lung-cancer-screening" },
    tags: ["がん検診", "肺癌", "USPSTF", "予防"]
  },
  {
    id: "cl-divertic-01",
    category: "clinical",
    difficulty: 2,
    added: "2026-07-19",
    question: "CTで確定した急性単純性(合併症のない)大腸憩室炎で、全身状態が良好・免疫正常の外来成人への抗菌薬治療について、近年のエビデンス・ガイドライン(AGA/ASCRS等)が支持する方針はどれか。",
    options: ["全例で広域抗菌薬の静注を要する", "入院のうえ最低10日間の抗菌薬を投与する", "抗菌薬に加えルーチンで待機的大腸切除を行う", "全身状態が安定し免疫正常なら抗菌薬は必須でなく選択的に用いる"],
    correct: 3,
    explanation: "【要点】合併症のない急性憩室炎で全身状態良好・免疫正常の患者では、抗菌薬は必須ではなく選択的使用が支持される。\n【エビデンス】AVOD・DIABOLOなどのRCTで、抗菌薬非投与は回復期間・合併症・再発率で抗菌薬投与に非劣性。AGA・ASCRSは選択的使用を、NICEも全身状態良好例では非投与を提案する。\n【臨床応用】十分な経口摂取・良好な疼痛管理・確実なフォローが可能な外来例が対象。免疫不全、敗血症徴候、膿瘍・穿孔・瘻孔などの合併症、経口摂取不良では抗菌薬(±入院)を要する。\n【誤答】全例静注・一律10日投与・ルーチン切除は過剰で、抗菌薬適正使用に反する。",
    source: { title: "Things We Do for No Reason: Routine use of antibiotics for acute uncomplicated diverticulitis (PubMed)", url: "https://pubmed.ncbi.nlm.nih.gov/39910717/" },
    tags: ["憩室炎", "抗菌薬適正使用", "消化器", "外来"]
  },
  {
    id: "jr-step9oa-01",
    category: "journal",
    difficulty: 2,
    added: "2026-07-19",
    question: "肥満を伴う膝変形性関節症(中等度のX線変化)の成人を対象に、週1回セマグルチド2.4mgをプラセボと比較したSTEP 9試験(NEJM 2024)の主要結果はどれか。",
    options: ["体重を有意に減少させ、膝OA関連の疼痛(WOMAC)も有意に改善した", "体重は減少したが疼痛はプラセボと差がなかった", "疼痛は改善したが体重に有意差はなかった", "体重・疼痛のいずれも改善しなかった"],
    correct: 0,
    explanation: "【要点】STEP 9では、セマグルチド2.4mgは体重を有意に減らし、膝OA関連疼痛(WOMACペインスコア)も有意に改善した。\n【背景/エビデンス】肥満+膝OA(Kellgren-Lawrence 2〜3)の407例を68週間検討。WOMAC疼痛の変化は−41.7 vs プラセボ−27.5、体重は約−13.7% vs −3.2%。身体機能(SF-36)も改善した。\n【臨床応用】肥満が一因の膝OAで、減量薬が疼痛・機能改善やNSAID減量の一助となりうる。OA特異的治療の置換ではなく、運動療法・減量の枠内で位置づける。消化器有害事象と用量漸増に留意。\n【誤答】疼痛・体重の一方のみ改善、または両者とも改善せず、はいずれも結果と異なる。",
    source: { title: "Once-Weekly Semaglutide in Persons with Obesity and Knee Osteoarthritis (STEP 9, NEJM 2024)", url: "https://www.nejm.org/doi/full/10.1056/NEJMoa2403664" },
    tags: ["肥満", "変形性関節症", "GLP-1", "セマグルチド"]
  },
  {
    id: "gl-psa-01",
    category: "guideline",
    difficulty: 2,
    added: "2026-07-19",
    question: "前立腺癌に対するPSAスクリーニングについて、2018年USPSTF勧告に沿った記述として正しいものはどれか。",
    options: ["70歳以上ではルーチンのスクリーニングは推奨されない(Grade D)", "55〜69歳では利益と不利益を説明したうえで個別に共有意思決定して判断する(Grade C)", "PSA上昇があれば確認検査なしに直ちに前立腺全摘を行う", "全男性に40歳から一律で年1回のPSA検査を推奨する"],
    correct: [0, 1],
    explanation: "【要点】2018 USPSTFは、55〜69歳のPSAスクリーニングを利益・不利益の説明に基づく個別の共有意思決定(Grade C)とし、70歳以上ではルーチンのスクリーニングを推奨しない(Grade D)。\n【背景/エビデンス】2012年の『全年齢で非推奨(D)』から55〜69歳で個別判断へ緩和。PSAは前立腺癌死をある程度減らしうる一方、過剰診断・過剰治療(失禁・EDなど)の不利益がある。家族歴・人種(黒人)・併存症・価値観を踏まえて相談する。\n【臨床応用】検査前に利益・不利益を説明し希望を確認する。\n【誤答】40歳から一律推奨、PSA上昇で確認なしに全摘は、いずれも勧告に反し過剰。",
    source: { title: "Final Recommendation Statement: Screening for Prostate Cancer (USPSTF 2018)", url: "https://www.uspreventiveservicestaskforce.org/uspstf/announcements/final-recommendation-statement-screening-prostate-cancer" },
    tags: ["がん検診", "前立腺癌", "USPSTF", "複数選択"]
  },
  {
    id: "rv-menopause-01",
    category: "review",
    difficulty: 2,
    added: "2026-07-19",
    question: "閉経後女性の血管運動症状(ホットフラッシュ等)に対するホルモン療法(HT)について、The Menopause Society(旧NAMS)2022ポジションステートメントに沿った記述として正しいものはどれか。",
    options: ["60歳未満かつ閉経後10年以内の健康な有症状女性では多くの場合ベネフィットがリスクを上回る", "血管運動症状に対する最も有効な治療である", "年齢や閉経からの期間を問わず全ての閉経後女性に一律の長期投与を推奨する", "経皮投与や低用量は経口に比べVTE・脳卒中リスクを低減しうる"],
    correct: [0, 1, 3],
    explanation: "【要点】TMS(旧NAMS)2022声明は、HTが血管運動症状に最も有効で、60歳未満かつ閉経後10年以内の健康な有症状女性では多くの場合ベネフィットがリスクを上回るとする。経皮・低用量はVTE/脳卒中リスクを下げうる。\n【背景/エビデンス】ベネフィット・リスクは開始年齢と閉経からの期間に依存(timing hypothesis)。60〜65歳以降の新規開始・長期使用の乳癌等リスクに関するRCTデータは限られる。\n【臨床応用】用量・期間・投与経路を個別化し、共有意思決定と定期的な再評価を行う。子宮を有する女性ではプロゲスチン併用が必要。\n【誤答】年齢や期間を問わず全員に一律長期投与、は個別化原則に反する。",
    source: { title: "The 2022 Hormone Therapy Position Statement of The North American Menopause Society", url: "https://menopause.org/wp-content/uploads/press-release/ht-position-statement-release.pdf" },
    tags: ["更年期", "ホルモン療法", "血管運動症状", "複数選択"]
  },
  {
    id: "gl-migraine-01",
    category: "guideline",
    difficulty: 2,
    added: "2026-07-19",
    question: "反復性/慢性片頭痛の予防治療について、米国頭痛学会(AHS)2024年ポジションステートメントが示した方針はどれか。",
    options: ["CGRP標的治療は他クラスの予防薬で複数回失敗した後にのみ使用できる", "CGRP標的治療(抗体薬およびgepant)は従来薬の事前失敗を要件とせず第一選択の予防選択肢としてよい", "予防治療の第一選択はオピオイドの定期内服である", "片頭痛予防では非薬物療法のみが推奨され薬物予防は行わない"],
    correct: 1,
    explanation: "【要点】AHS 2024声明は、CGRP標的治療(erenumab等の抗体薬、rimegepant/atogepant等のgepant)を、他クラスの予防薬の事前失敗を要件とせず第一選択の予防オプションとしてよいとした。\n【背景/エビデンス】有効性・忍容性・安全性のエビデンスが従来の予防薬を大きく上回ることが根拠。従来はβ遮断薬・抗てんかん薬・三環系抗うつ薬などの失敗後に用いる位置づけだった。\n【臨床応用】発作頻度・障害度・併存症・患者希望を踏まえ早期からの導入を検討できる。rimegepantは反復性、atogepantは反復性・慢性で予防適応。\n【誤答】複数回失敗後のみ・オピオイド定期内服・非薬物のみは、いずれも現行の推奨に反する。",
    source: { title: "AHS Position Statement: CGRP-targeting therapies as first-line for migraine prevention (2024)", url: "https://www.migrainedisorders.org/ahs-statement-cgrp/" },
    tags: ["片頭痛", "CGRP", "予防治療", "神経"]
  },
  {
    id: "rv-aud-01",
    category: "review",
    difficulty: 1,
    added: "2026-07-20",
    question: "アルコール使用障害(AUD)に対する薬物療法で、心理社会的支援と併用する第一選択薬として位置づけられるものはどれか。",
    options: ["ジスルフィラム", "ナルトレキソン", "トピラマート", "アカンプロサート"],
    correct: [1, 3],
    explanation: "【要点】AUDの薬物療法で第一選択に位置づけられるのはナルトレキソンとアカンプロサートであり、いずれもカウンセリング・自助グループなどの心理社会的介入と併用する。\n【背景/エビデンス】APA等のガイドラインが両薬を推奨。ナルトレキソン(μオピオイド受容体拮抗)は飲酒欲求・多量飲酒を減らし、月1回の持効性筋注もある。アカンプロサートはグルタミン酸系を調整し断酒維持に有効で、腎排泄のため肝障害例でも使いやすい。\n【臨床応用】併存症とアドヒアランスで使い分ける(オピオイド使用中はナルトレキソン不可、重度腎障害ではアカンプロサート不可)。\n【誤答】ジスルフィラム(嫌酒薬)やトピラマートも有効だが、通常は第一選択ではなく二次的な選択肢である。",
    source: { title: "Alcohol Use Disorder: Pharmacologic Treatment Options (AAFP)", url: "https://www.aafp.org/afp/2020/1001/od1" },
    tags: ["アルコール使用障害", "ナルトレキソン", "アカンプロサート", "複数選択"]
  },
  {
    id: "cl-aud-01",
    category: "clinical",
    difficulty: 2,
    added: "2026-07-20",
    question: "非代償性肝硬変を合併するアルコール使用障害の患者で、断酒維持のための薬物療法として最も適切なのはどれか。",
    options: ["ジスルフィラム", "ナルトレキソン", "アカンプロサート", "高用量ベンゾジアゼピンの長期投与"],
    correct: 2,
    explanation: "【要点】非代償性肝硬変を伴うAUDでは、肝代謝を受けず腎排泄されるアカンプロサートが断酒維持の第一選択となる。\n【理由】ナルトレキソンは肝毒性の懸念があり急性肝炎・肝不全では禁忌/回避が原則。ジスルフィラムはアセトアルデヒド反応と肝毒性のため重症肝疾患では避ける。アカンプロサートは肝で代謝されず比較的安全に使える(ただしCrCl<30の重度腎障害では禁忌)。\n【臨床応用】飲酒欲求の軽減と再飲酒予防を狙い、心理社会的支援と併用する。腎機能を確認して用量を調整する。\n【誤答】ベンゾジアゼピンは離脱期の短期使用に限られ、長期投与は依存・転倒・認知への悪影響から維持療法にはならない。",
    source: { title: "Alcohol Use Disorder: Pharmacologic Treatment Options (AAFP)", url: "https://www.aafp.org/afp/2020/1001/od1" },
    tags: ["アルコール使用障害", "肝硬変", "アカンプロサート"]
  },
  {
    id: "gl-acs-01",
    category: "guideline",
    difficulty: 2,
    added: "2026-07-20",
    question: "2025 ACC/AHA急性冠症候群(ACS)ガイドラインにおける脂質管理の初期方針として適切なものはどれか。",
    options: ["全例で高強度スタチンを開始し、必要に応じて開始時からエゼチミブの併用も考慮する", "LDL値にかかわらず脂質降下薬は退院後に開始する", "低強度スタチンを基本とする", "スタチンは避けPCSK9阻害薬を単独で用いる"],
    correct: 0,
    explanation: "【要点】2025 ACC/AHA ACSガイドラインは、全ACS患者への高強度スタチンを推奨し、開始時からのエゼチミブ併用も選択肢とする。\n【背景/エビデンス】最大耐用量スタチンでもLDL≥70mg/dLなら、エゼチミブ、PCSK9阻害薬(エボロクマブ/アリロクマブ)、インクリシラン、ベンペド酸などの非スタチン薬を上乗せする。早期からの積極的なLDL低下が再発予防に寄与する('lower is better')。\n【臨床応用】入院中に高強度スタチンを開始し、脂質を再検して目標未達なら段階的に上乗せする。\n【誤答】低強度スタチン・退院後開始・スタチン回避は、いずれも現行の積極的なLDL低下方針に反する。",
    source: { title: "2025 ACC/AHA Guideline for the Management of Patients With Acute Coronary Syndromes (Circulation)", url: "https://www.ahajournals.org/doi/10.1161/CIR.0000000000001309" },
    tags: ["ACS", "脂質", "高強度スタチン", "エゼチミブ"]
  },
  {
    id: "cl-acs-01",
    category: "clinical",
    difficulty: 3,
    added: "2026-07-20",
    question: "PCIを受けたACS患者。チカグレロルを含むDAPTを約1か月良好に忍容したが出血リスクが高い。2025 ACC/AHAガイドラインに沿った抗血小板療法の調整として妥当なものはどれか。",
    options: ["アスピリン単剤に切り替える", "両剤を高用量へ増量する", "抗血小板薬をすべて中止する", "チカグレロル単剤療法へ移行する(PCI後1か月以降)"],
    correct: 3,
    explanation: "【要点】チカグレロルを含むDAPTを忍容した患者では、PCI後1か月以降にチカグレロル単剤療法へ移行することで、虚血予防を保ちつつ出血を減らせる。\n【背景/エビデンス】TWILIGHT等を反映し、2025 ACC/AHA ACSガイドラインは高出血リスク例での早期のP2Y12阻害薬単剤化を推奨。消化管出血リスク例ではPPI併用、経口抗凝固薬併用例ではPCI後1〜4週でアスピリンを中止しP2Y12阻害薬(クロピドグレル推奨)を継続する。\n【臨床応用】出血・虚血リスクを個別に評価し、脱アスピリンのタイミングを判断する。\n【誤答】アスピリン単剤化・全中止・両剤増量は、出血や再発のリスクの点で不適切。",
    source: { title: "2025 ACC/AHA Guideline for the Management of Patients With Acute Coronary Syndromes (Circulation)", url: "https://www.ahajournals.org/doi/10.1161/CIR.0000000000001309" },
    tags: ["ACS", "抗血小板薬", "DAPT", "出血リスク"]
  },
  {
    id: "jr-ironhf-01",
    category: "journal",
    difficulty: 2,
    added: "2026-07-20",
    question: "鉄欠乏を伴う心不全患者への静脈内鉄補充について、複数RCTを統合した近年のメタ解析(FAIR-HF/CONFIRM-HF/AFFIRM-AHF/IRONMAN/HEART-FID等)が示した所見として最も適切なものはどれか。",
    options: ["全死亡を確実に半減させた", "心不全入院(および心血管死との複合)を有意に減少させた", "アウトカムに影響しなかった", "むしろ心不全入院を増やした"],
    correct: 1,
    explanation: "【要点】鉄欠乏を伴う心不全への静脈内鉄補充は、心不全入院(および心血管死との複合)を有意に減少させる。\n【背景/エビデンス】6試験・約7000例超を統合したメタ解析で、複合エンドポイントのリスクが約2〜3割低下(12か月でRR≈0.72)。HEART-FIDやIRONMANなど個々の試験は主要評価を僅差で外したが、統合すると入院抑制が一貫。一方で全死亡の明確な低下は確立していない。\n【臨床応用】症候性HFrEF(一部HFmrEF)でフェリチン<100、またはフェリチン100〜300かつTSAT<20%の鉄欠乏を評価し、静注鉄(カルボキシマルトース第二鉄等)を検討する。\n【誤答】全死亡半減・効果なし・入院増加は、いずれもデータと異なる。",
    source: { title: "Systematic review and meta-analysis of intravenous iron therapy for patients with heart failure and iron deficiency (Nature Medicine 2025)", url: "https://www.nature.com/articles/s41591-025-03671-1" },
    tags: ["心不全", "鉄欠乏", "静注鉄", "HFrEF"]
  },
  {
    id: "gl-rls-01",
    category: "guideline",
    difficulty: 2,
    added: "2026-07-20",
    question: "むずむず脚症候群(RLS)の治療に関する2024年AASMガイドラインの方針として妥当なものはどれか。",
    options: ["α2δリガンド(ガバペンチン エナカルビル/ガバペンチン/プレガバリン)を主要な治療選択肢とする", "血清フェリチン低値では鉄補充を行う", "ドパミン作動薬(プラミペキソール等)を長期の定期治療の第一選択とする", "増強現象(augmentation)のリスクからドパミン作動薬の標準的使用は推奨しない"],
    correct: [0, 1, 3],
    explanation: "【要点】2024 AASMガイドラインは、α2δリガンド(ガバペンチン エナカルビル、ガバペンチン、プレガバリン)と鉄補充を中心に据え、ドパミン作動薬の標準的使用を推奨しないという大きな方針転換を示した。\n【背景/エビデンス】ドパミン作動薬は長期使用で増強現象(症状の悪化・出現時間の前倒し)を招くため、従来の第一選択の位置づけから外れた。鉄はフェリチン/TSATを評価し(目安フェリチン>75〜100、TSAT>20%)、経口または静注で補充する。\n【臨床応用】まず鉄評価と是正を行い、症候例にはα2δリガンドを検討する。\n【誤答】ドパミン作動薬を長期の定期治療の第一選択とするのは、増強現象の観点から現行方針に反する。",
    source: { title: "Summary of the 2024 AASM Clinical Practice Guideline for RLS and PLMD", url: "https://aasm.org/summary-of-new-clinical-practice-guideline-for-rls-and-plmd/" },
    tags: ["むずむず脚症候群", "α2δリガンド", "鉄補充", "複数選択"]
  },
  {
    id: "cl-htn-02",
    category: "clinical",
    difficulty: 3,
    added: "2026-07-21",
    question: "58歳、真の治療抵抗性高血圧。ACE阻害薬/ARB・カルシウム拮抗薬・サイアザイド系利尿薬を最大耐用量で用い、スピロノラクトンを追加してもなお診察室血圧が目標未達。アドヒアランス不良や二次性高血圧は評価済みである。近年承認され、この段階の上乗せ治療の選択肢になりうる薬剤はどれか。",
    options: ["α遮断薬(ドキサゾシン)への一本化", "経口ミノキシジルの少量追加", "ループ利尿薬をサイアザイドの代わりに常用へ変更", "デュアルエンドセリン受容体拮抗薬アプロシテンタンの追加"],
    correct: 3,
    explanation: "【要点】標準4剤(RAS阻害薬・CCB・利尿薬・MRA)でも未達の真の治療抵抗性高血圧では、2024年に承認されたデュアルエンドセリン受容体拮抗薬アプロシテンタンが追加の選択肢となる。\n【背景/エビデンス】第3相PRECISION試験(730例、amlodipine/valsartan/HCTZの固定併用下)で、アプロシテンタン12.5/25mgは4週で診察室・24時間血圧をプラセボより有意に低下させ、40週まで効果が持続した。主な有害事象は用量依存性の軽〜中等度の浮腫/体液貯留。\n【臨床応用/注意】体液貯留・貧血に留意し、催奇形性の懸念から妊娠可能女性では避ける。心不全での体液管理に注意し、導入前にアドヒアランスと二次性要因の評価を済ませておく。\n【誤答】ミノキシジル・ループ利尿薬への変更・α遮断薬はいずれも抵抗例で用いられうるが、本問で問われた『近年承認された新規機序の薬』ではない。",
    source: { title: "Dual endothelin antagonist aprocitentan for resistant hypertension (PRECISION): a phase 3 trial (Lancet)", url: "https://pubmed.ncbi.nlm.nih.gov/36356632/" },
    tags: ["高血圧", "治療抵抗性", "アプロシテンタン", "エンドセリン"]
  },
  {
    id: "jr-baxhtn-01",
    category: "journal",
    difficulty: 2,
    added: "2026-07-21",
    question: "選択的アルドステロン合成酵素阻害薬バクスドロスタットについて、第3相BaxHTN試験の結果および使用上の留意点として適切なものはどれか。",
    options: ["アルドステロンを抑制するため高カリウム血症のモニタリングが必要で、コントロール不良/抵抗性高血圧の収縮期血圧を有意に低下させた", "主にコルチゾール合成を阻害するためグルココルチコイド補充が必須である", "血圧低下は得られたが低カリウム血症が問題となった", "ミネラルコルチコイド受容体を遮断する点でスピロノラクトンと同一機序である"],
    correct: 0,
    explanation: "【要点】バクスドロスタットはアルドステロン合成酵素(CYP11B2)を選択的に阻害する新規降圧薬で、BaxHTN試験でコントロール不良/治療抵抗性高血圧の収縮期血圧を有意に低下させた。アルドステロン抑制に伴う高カリウム血症のモニタリングが必要。\n【背景/エビデンス】標準治療への上乗せで、プラセボ補正でおよそ収縮期9〜10mmHgの低下(2mgで24時間SBPを約17mmHg低下)。2025年ESCで発表されNEJMに同時掲載された。CYP11B1(コルチゾール)への選択性が高く、副腎不全は起こしにくい設計。\n【臨床応用/注意】導入後はカリウム・ナトリウムと腎機能をモニタリングする。\n【誤答】機序はMR遮断(スピロノラクトン)ではなく合成阻害であり、コルチゾール阻害主体でもなく、注意すべきは低Kではなく高Kである。",
    source: { title: "Baxdrostat and the future of aldosterone-targeted therapy (Hypertension Research 2025)", url: "https://www.nature.com/articles/s41440-025-02415-5" },
    tags: ["高血圧", "治療抵抗性", "バクスドロスタット", "アルドステロン合成酵素"]
  },
  {
    id: "jr-icodec-01",
    category: "journal",
    difficulty: 2,
    added: "2026-07-21",
    question: "週1回投与の基礎インスリン イコデクを2型糖尿病で1日1回基礎インスリンと比較したONWARDSプログラムの知見として適切なものはどれか。",
    options: ["重症低血糖が1日1回製剤より大幅に多く、開発が中止された", "HbA1c低下は1日1回製剤に非劣性で一部試験では優越、重症低血糖は概ね同等だった", "血糖は改善したが注射回数が増え利便性が低下した", "1型糖尿病でのみ有効で2型では無効だった"],
    correct: 1,
    explanation: "【要点】週1回基礎インスリン イコデクは、2型糖尿病でHbA1c低下について1日1回基礎インスリンに非劣性で、ONWARDS 1・2・3・5では優越を示し、重症低血糖はおおむね同等だった。\n【背景/エビデンス】ONWARDS 1〜5(インスリン未使用例・切替例を含む)で推定治療差はHbA1cで概ね−0.1〜−0.2%程度。臨床的に重要/重症の低血糖の頻度は1日1回製剤と同等で、デグルデクとの比較では重症低血糖がむしろ少ない報告もある。\n【臨床応用/注意】注射が年52回で済み負担軽減が期待できる一方、週1回のため低血糖時の用量調整はより慎重を要し、導入初期や食事変動時のモニタリングが重要。\n【誤答】開発中止・利便性低下・1型限定は、いずれも知見と異なる。",
    source: { title: "Weekly Icodec versus Daily Glargine U100 in Type 2 Diabetes without Previous Insulin (ONWARDS 1, NEJM)", url: "https://www.nejm.org/doi/full/10.1056/NEJMoa2303208" },
    tags: ["糖尿病", "インスリン", "イコデク", "週1回"]
  },
  {
    id: "gl-cervical-01",
    category: "guideline",
    difficulty: 1,
    added: "2026-07-21",
    question: "子宮頸がん検診に関する近年の米国の方針(USPSTF 2025ドラフト/ACS 2025更新)で新たに取り入れられた点はどれか。",
    options: ["21歳未満から細胞診を開始する", "30歳以上では毎年のHPV検査を必須とする", "30〜65歳で、自己採取を含む高リスクHPV検査を5年ごとの一次スクリーニングとして許容する", "適切な検診歴の有無にかかわらず65歳以上は全例で生涯検診を継続する"],
    correct: 2,
    explanation: "【要点】近年の米国方針は、30〜65歳で高リスクHPV(hrHPV)一次スクリーニングを5年ごととし、医療者採取に加えて自己採取(セルフサンプリング)を許容する点が新しい。\n【背景/エビデンス】2024年にFDAが自己採取HPV検査を承認し、USPSTF 2025ドラフトおよびACS 2025更新が自己採取を選択肢に加えた。21〜29歳は細胞診を3年ごと。自己採取は受検率向上・アクセス改善が期待され、グレードAの一次HPV検診の枠内に位置づけられる。\n【臨床応用/注意】陽性例はコルポスコピー等の精査へ進める。適切な検診歴があり基準を満たせば65歳での終了を検討する。制度・保険適用は地域により異なる。\n【誤答】21歳未満開始・毎年HPV・65歳以上の一律継続は、いずれも現行の方向と異なる。",
    source: { title: "American Cancer Society Updates Cervical Cancer Screening Guideline: Self-Collection for HPV Testing (2025)", url: "https://pressroom.cancer.org/updated-cervical-cancer-screening-guidelines-2025" },
    tags: ["がん検診", "子宮頸がん", "HPV", "自己採取"]
  },
  {
    id: "gl-cdiff-01",
    category: "guideline",
    difficulty: 2,
    added: "2026-07-21",
    question: "成人の初発Clostridioides difficile感染症(CDI)の治療に関して、2021年SHEA/IDSAアップデートに沿った方針はどれか。",
    options: ["フィダキソマイシンを標準的なバンコマイシン経口より優先することが提案される", "フィダキソマイシンが使えない場合、バンコマイシン経口は許容される代替である", "経口メトロニダゾールを初発の第一選択とする", "可能なら原因となっている抗菌薬を中止・再評価する"],
    correct: [0, 1, 3],
    explanation: "【要点】2021 SHEA/IDSAアップデートは、初発CDIでフィダキソマイシンをバンコマイシン経口より優先することを提案した(条件付き推奨)。バンコマイシン経口は許容される代替であり、誘因となる抗菌薬の中止・再評価は基本原則である。\n【背景/エビデンス】フィダキソマイシンは再発を減らす点でバンコマイシンに優る(条件付き・中等度の確実性)。経口メトロニダゾールは有効性が劣るため、他剤が使えない非重症例に限る位置づけへ後退した。実地では費用・入手性から採用が緩やかな面もある。\n【臨床応用/注意】重症度評価、可能な原因抗菌薬の中止、再発時の戦略(フィダキソマイシンの延長/パルス漸減、ベズロトクスマブ、便微生物移植)を個別化する。\n【誤答】メトロニダゾールを初発の第一選択とするのは現行では非推奨で、この設問の文脈では不適切。",
    source: { title: "SHEA/IDSA 2021 Focused Update Guidelines on Management of Clostridioides difficile Infection in Adults", url: "https://www.idsociety.org/practice-guideline/clostridioides-difficile-2021-focused-update/" },
    tags: ["感染症", "CDI", "フィダキソマイシン", "複数選択"]
  },
  {
    id: "rv-saltsub-01",
    category: "review",
    difficulty: 2,
    added: "2026-07-21",
    question: "高血圧・脳卒中予防を目的に、カリウム富化塩(塩化ナトリウムの一部を塩化カリウムに置換した代替塩)への切替を検討する際、大規模クラスター無作為化試験SSaSSが示した知見として適切なものはどれか。",
    options: ["血圧は下がったが脳卒中・心血管イベントは減らなかった", "脳卒中・主要心血管イベント・総死亡をいずれも有意に低下させた", "効果はあったが重症腎障害を含む全患者で高カリウム血症が問題となった", "血圧・イベントとも有意な変化はなかった"],
    correct: 1,
    explanation: "【要点】SSaSSでは、カリウム富化塩(NaCl約75%+KCl約25%)への切替が脳卒中・主要心血管イベント・総死亡をいずれも有意に低下させた。\n【背景/エビデンス】脳卒中既往または60歳以上で高血圧をもつ中国農村の20,995人・600村を対象としたクラスター無作為化、約5年。脳卒中−14%、主要心血管イベント−13%、総死亡−12%、収縮期血圧は約3.3mmHg低下。重症腎障害・カリウム保持性利尿薬使用者は除外され、臨床的高カリウム血症の全体的な増加はみられなかった。\n【臨床応用/注意】腎機能が正常でカリウム制限の不要な高血圧・脳卒中リスク者では、簡便で費用対効果の高い介入となりうる。一方、CKD進行例、カリウム保持性利尿薬/RAS阻害薬併用の高K傾向例、アルドステロン低下病態では避けるか慎重に用いる。\n【誤答】イベント減少なし・変化なし・全例で高K問題化は、いずれも試験結果と異なる。",
    source: { title: "Effect of Salt Substitution on Cardiovascular Events and Death (SSaSS, NEJM 2021)", url: "https://www.nejm.org/doi/full/10.1056/NEJMoa2105675" },
    tags: ["高血圧", "減塩", "カリウム", "脳卒中予防"]
  },
  {
    id: "jr-dupicopd-01",
    category: "journal",
    difficulty: 2,
    added: "2026-07-22",
    question: "2型炎症を伴うCOPDに対する生物学的製剤デュピルマブについて、BOREAS/NOTUS試験に基づき妥当な記述はどれか。",
    options: ["好酸球数によらず全COPD患者で増悪抑制が確立している", "IL-4/IL-13の共有受容体をブロックするモノクローナル抗体である", "気管支拡張薬でありLAMA/LABAを置換する位置づけである", "標準吸入トリプル療法に上乗せし、血中好酸球高値(2型炎症)のCOPDで増悪を有意に減少させた"],
    correct: [1, 3],
    explanation: "【要点】デュピルマブは、血中好酸球高値(2型炎症)を伴うCOPDで、標準吸入トリプル療法に上乗せして増悪を有意に減らす初のバイオ製剤である。IL-4/IL-13の共有受容体をブロックする。\n【背景/エビデンス】BOREASと確認試験NOTUSは血中好酸球≥300/μLの中等症〜重症COPD計1,874例を対象。52週で年間増悪をプラセボ比で有意に低下(NOTUSで約34%減)、肺機能(FEV1)も改善した。\n【臨床応用/注意】適応の中心は2型炎症のバイオマーカーである好酸球高値例で、既にICS/LABA/LAMAを最適化しても増悪を繰り返す患者に追加する。気管支拡張薬の代替ではない。\n【誤答】『好酸球によらず全例で確立』は誤りで、対象は好酸球高値例。『LAMA/LABAを置換する気管支拡張薬』も機序・位置づけが異なり、この文脈で不適切。",
    source: { title: "Dupilumab for COPD with Blood Eosinophil Evidence of Type 2 Inflammation (NOTUS, NEJM 2024)", url: "https://www.nejm.org/doi/full/10.1056/NEJMoa2401304" },
    tags: ["COPD", "デュピルマブ", "2型炎症", "複数選択"]
  },
  {
    id: "jr-abelacimab-01",
    category: "journal",
    difficulty: 3,
    added: "2026-07-22",
    question: "心房細動患者を対象に抗凝固薬アベラシマブとリバーロキサバンを比較したAZALEA-TIMI 71試験に関して、適切な記述はどれか。",
    options: ["リバーロキサバンと比べ大出血および臨床的に重要な非大出血を大幅に減少させた", "脳卒中・全身塞栓の予防における優越性が本試験で確定的に示された", "標的は凝固第XI因子で、内因系凝固を抑制する", "月1回皮下投与のモノクローナル抗体である"],
    correct: [0, 2, 3],
    explanation: "【要点】アベラシマブは第XI因子を標的とする月1回皮下投与のモノクローナル抗体で、AZALEA-TIMI 71ではリバーロキサバンと比べ出血を大幅に減らした。\n【背景/エビデンス】心房細動1,287例を対象とし、150mg群で大出血/臨床的に重要な非大出血を約67%、大出血を約74%、消化管出血を約93%減少。出血の圧倒的減少により試験は早期中止された。\n【臨床応用/注意】第XI因子阻害は止血に必要なトロンビン生成を比較的保ちつつ病的血栓を抑える戦略として期待される。ただし本試験は脳卒中予防の優越性を検出する検出力はなく、有効性は今後の大規模試験(第III相)待ちである。\n【誤答】『脳卒中予防の優越性が確定的に示された』はイベント数が少なく確定できておらず、この文脈で不適切。他の3つは試験・機序と整合する。",
    source: { title: "AZALEA-TIMI 71: Abelacimab vs Rivaroxaban in Atrial Fibrillation (TCTMD/TIMI 2024)", url: "https://www.tctmd.com/news/azalea-timi-71-abelacimab-slashes-bleeds-vs-rivaroxaban-af-stroke-impact-unclear" },
    tags: ["心房細動", "第XI因子", "抗凝固", "複数選択"]
  },
  {
    id: "cl-aprocitentan-01",
    category: "clinical",
    difficulty: 3,
    added: "2026-07-22",
    question: "二次性高血圧を除外済みで、スピロノラクトンを含む4剤併用でも血圧管理が困難な真の治療抵抗性高血圧の成人。近年承認された新規機序の追加薬として支持されるのはどれか。",
    options: ["アプロシテンタン(デュアルエンドセリン受容体拮抗薬)を追加する", "サイアザイド系利尿薬をさらに増量する", "長時間作用型硝酸薬を追加する", "第一選択としてドキサゾシン(α遮断薬)を用いる"],
    correct: 0,
    explanation: "【要点】スピロノラクトンを含む多剤でも未達の真の治療抵抗性高血圧では、デュアルエンドセリン受容体拮抗薬アプロシテンタンが新規の追加選択肢として支持される。\n【背景/エビデンス】PRECISION試験(第III相)で、標準3剤に上乗せしたアプロシテンタンは4週で24時間収縮期血圧を追加で有意に低下(用量依存的に約4〜6mmHg)、40週まで効果が持続した。主な有害事象は軽〜中等度の浮腫・体液貯留。\n【臨床応用/注意】アドヒアランス・二次性要因を評価し、既存レジメン最適化後に検討する。体液貯留や心不全リスク、妊娠回避に留意する。\n【誤答】サイアザイド増量やドキサゾシンは既存クラス内の一手で『新規機序』に当たらず、硝酸薬は降圧の主役でない。いずれも本設問(新規承認機序)の文脈では最適でない。",
    source: { title: "Dual Endothelin Antagonist Aprocitentan for Resistant Hypertension (PRECISION, Lancet 2022)", url: "https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(22)02034-7/abstract" },
    tags: ["高血圧", "治療抵抗性", "アプロシテンタン", "エンドセリン"]
  },
  {
    id: "gl-anxiety-01",
    category: "guideline",
    difficulty: 1,
    added: "2026-07-22",
    question: "2023年 米国USPSTFの成人に対する不安症スクリーニング勧告の内容として正しいものはどれか。",
    options: ["65歳超を含む全成人に推奨する(Grade A)", "症状のない19〜64歳の成人(妊娠・産後を含む)にスクリーニングを推奨する(Grade B)", "スクリーニングは有害でありルーチンには推奨しない(Grade D)", "対象は小児・思春期のみである"],
    correct: 1,
    explanation: "【要点】2023年USPSTFは、症状のない19〜64歳の成人(妊娠・産後を含む)に対する不安症のスクリーニングをGrade Bで推奨した。成人への不安症スクリーニングの推奨は初。\n【背景/エビデンス】不安症は頻度が高く過小診断されがちで、GAD-7等の妥当性ある簡便ツールで拾い上げ、治療につなげる便益が中等度と判断された。65歳超では証拠不十分(I statement)で、推奨・非推奨いずれも表明していない。\n【臨床応用/注意】あくまで無症状者への系統的スクリーニングの話で、陽性例は診断的評価と重症度・自殺リスク評価につなげる。うつ病スクリーニング(成人でGrade B)と併せて運用する。\n【誤答】『全成人にGrade A』『Grade Dで非推奨』『小児のみ』は、いずれも実際の勧告と異なる。",
    source: { title: "Anxiety Disorders in Adults: Screening — USPSTF Recommendation (2023)", url: "https://www.uspreventiveservicestaskforce.org/uspstf/recommendation/anxiety-adults-screening" },
    tags: ["メンタルヘルス", "不安症", "USPSTF", "スクリーニング"]
  },
  {
    id: "rv-ensifentrine-01",
    category: "review",
    difficulty: 2,
    added: "2026-07-22",
    question: "COPDの維持療法として2024年に承認された吸入薬エンシフェントリンの薬理学的分類はどれか。",
    options: ["長時間作用型β2刺激薬(LABA)", "吸入ステロイド(ICS)", "ロイコトリエン受容体拮抗薬", "PDE3/PDE4のデュアル阻害薬で、気管支拡張と抗炎症作用を併せ持つ"],
    correct: 3,
    explanation: "【要点】エンシフェントリン(Ohtuvayre)は、PDE3とPDE4を同時に阻害する初のクラスの吸入維持療法薬で、気管支拡張と非ステロイド性の抗炎症作用を併せ持つ。COPD維持治療薬としては約20年ぶりの新規機序。\n【背景/エビデンス】第III相ENHANCE-1/2(中等症〜重症COPD計1,553例、24週)で肺機能(FEV1)・症状・QOLを有意に改善。増悪リスクはENHANCE-2で低下したがENHANCE-1では有意でなかった。\n【臨床応用/注意】PDE3/PDE4阻害によりcAMP/cGMPを増やし気道平滑筋を弛緩させる。既存の吸入療法に上乗せする位置づけで、位置づけの確立には長期増悪データの蓄積が待たれる。\n【誤答】LABA・ICS・ロイコトリエン受容体拮抗薬はいずれも既存の別クラスで、エンシフェントリンの分類として不適切。",
    source: { title: "FDA Approves Ensifentrine for Maintenance Treatment of COPD (ENHANCE, AJMC 2024)", url: "https://www.ajmc.com/view/fda-approves-ensifentrine-for-maintenance-treatment-of-adult-patients-with-copd" },
    tags: ["COPD", "エンシフェントリン", "PDE阻害薬", "維持療法"]
  },
  {
    id: "jr-zilebesiran-01",
    category: "journal",
    difficulty: 2,
    added: "2026-07-22",
    question: "高血圧に対する新規薬ジレベシラン(KARDIA試験)の作用機序・特徴として正しいものはどれか。",
    options: ["アルドステロン合成酵素を阻害する新規経口薬である", "エンドセリン受容体を拮抗する新規薬である", "肝でのアンジオテンシノーゲン合成を標的とするRNAi治療で、皮下投与により降圧が長期間持続しうる", "新規クラスの経口カルシウム拮抗薬である"],
    correct: 2,
    explanation: "【要点】ジレベシランは、肝のアンジオテンシノーゲン(アンジオテンシンIIの前駆体)合成を抑えるRNAi治療で、皮下投与により数か月にわたる持続的な降圧が期待される。\n【背景/エビデンス】KARDIA-1(単剤)およびKARDIA-2(標準降圧薬への上乗せ)で、24時間収縮期血圧をプラセボ比で有意に低下(KARDIA-2で最大約12mmHgの追加低下)。半年に1回程度の投与でアドヒアランス課題の解決が期待される。\n【臨床応用/注意】GalNAc結合技術で肝選択的にRNAi作用を及ぼす。高カリウム血症・低血圧・妊娠時のRAS抑制リスクに留意が必要で、心血管アウトカムは今後の検証を要する。\n【誤答】アルドステロン合成酵素阻害薬(バクスドロスタット等)、エンドセリン受容体拮抗薬(アプロシテンタン)、カルシウム拮抗薬はいずれも別機序で、ジレベシランの分類として不適切。",
    source: { title: "RNA Interference With Zilebesiran for Mild to Moderate Hypertension (KARDIA-1, JAMA 2024)", url: "https://pubmed.ncbi.nlm.nih.gov/38363577/" },
    tags: ["高血圧", "ジレベシラン", "RNAi", "アンジオテンシノーゲン"]
  },
  {
    id: "jr-orforglipron-01",
    category: "journal",
    difficulty: 2,
    added: "2026-07-23",
    question: "経口の小分子(非ペプチド)GLP-1受容体作動薬オルフォルグリプロンを早期2型糖尿病に用いた第3相ACHIEVE-1試験で示された結果はどれか。",
    options: ["注射GLP-1薬と同じ骨格ペプチド構造をもち、皮下注射を要する", "血糖・体重ともにプラセボと有意差を示さなかった", "1日1回経口投与でHbA1cを最大約1.5%低下させ、体重も用量依存性に減少させた", "重症低血糖が高頻度に発生した"],
    correct: 2,
    explanation: "【要点】オルフォルグリプロンは1日1回経口投与の小分子(非ペプチド)GLP-1受容体作動薬で、早期2型糖尿病の第3相ACHIEVE-1試験でHbA1cと体重を有意に改善した。\n【背景/エビデンス】40週時点でHbA1cはプラセボの−0.4%に対し各用量で約−1.2〜−1.5%低下し、体重も3mg群−4.5%〜36mg群−7.6%と用量依存性に減少した。有害事象は用量漸増期に多い軽〜中等度の消化器症状が中心で、重症低血糖の報告はなかった。\n【臨床応用/注意】食事やペプチド薬のような投与制約が少ない経口薬として、注射に抵抗がある患者の選択肢となりうる。心血管アウトカムや長期安全性は今後の検証を要する。\n【誤答】ペプチド構造で皮下注射・血糖体重ともに差なし・重症低血糖多発は、いずれも試験結果や薬剤特性と異なる。",
    source: { title: "Orforglipron, an Oral Small-Molecule GLP-1 Receptor Agonist, in Early Type 2 Diabetes (ACHIEVE-1, NEJM 2025)", url: "https://www.nejm.org/doi/full/10.1056/NEJMoa2505669" },
    tags: ["糖尿病", "GLP-1", "経口薬", "オルフォルグリプロン"]
  },
  {
    id: "jr-obicetrapib-01",
    category: "journal",
    difficulty: 3,
    added: "2026-07-23",
    question: "CETP阻害薬オビセトラピブを、最大耐用量の脂質低下療法中の高リスク患者に用いた第3相BROADWAY試験について、妥当な記述はどれか。",
    options: ["1日1回経口投与で、LDLコレステロールをプラセボ比で約30%低下させた", "トルセトラピブと同様に血圧上昇・死亡増加により開発中止となった", "HDLコレステロールを低下させることで効果を発揮する", "スタチン等で目標未達の症例への上乗せ経口薬として位置づけられる"],
    correct: [0, 3],
    explanation: "【要点】オビセトラピブは経口CETP阻害薬で、BROADWAY試験では最大耐用量の脂質低下療法に上乗せしてLDLコレステロールをプラセボ比で約30%低下させ、目標未達例への追加経口薬として位置づけられる。\n【背景/エビデンス】確立ASCVDまたは家族性高コレステロール血症の2,530例が対象。84日目のLDL変化はオビセトラピブ−29.9%対プラセボ+2.7%で、有害事象は両群同程度だった。CETP阻害はLDLを下げHDLを上げる。\n【臨床応用/注意】スタチン・エゼチミブ・PCSK9阻害薬でも未達の高リスク例で有用となりうるが、心血管アウトカムの改善は今後の大規模試験を待つ必要がある。\n【誤答】トルセトラピブのような血圧上昇・死亡増加での中止や『HDL低下で効果』は、この薬の特性と異なりこの文脈で不適切。",
    source: { title: "Safety and Efficacy of Obicetrapib in Patients at High Cardiovascular Risk (BROADWAY, NEJM 2025)", url: "https://www.nejm.org/doi/abs/10.1056/NEJMoa2415820" },
    tags: ["脂質", "CETP阻害薬", "LDL", "複数選択"]
  },
  {
    id: "jr-lecanemab-01",
    category: "journal",
    difficulty: 3,
    added: "2026-07-23",
    question: "早期アルツハイマー病に対する抗アミロイドβ抗体レカネマブ(CLARITY-AD試験)に関して、妥当な記述はどれか。",
    options: ["認知機能低下を完全に停止させ、症状を回復させた", "18か月時点で認知・機能の低下をプラセボ比で中等度に緩やかにした", "脳内アミロイドを有意に減少させた", "ARIA(アミロイド関連画像異常:浮腫・微小出血)のモニタリングを要する"],
    correct: [1, 2, 3],
    explanation: "【要点】レカネマブは可溶性アミロイドβプロトフィブリルを標的とする抗体で、早期アルツハイマー病のCLARITY-AD試験で認知・機能低下を中等度に緩やかにし、脳内アミロイドを有意に減らした。ARIAのモニタリングを要する。\n【背景/エビデンス】MCIまたは軽度認知症でアミロイド陽性の50〜90歳、約1,795例を18か月追跡。主要評価CDR-SBの悪化を約27%抑制した。ARIA(浮腫ARIA-E・微小出血ARIA-H)が一定頻度で生じ、APOE ε4ホモ接合で高い。\n【臨床応用/注意】適応は早期例に限られ、アミロイド確認(PET/髄液)と定期MRIが前提。抗凝固併用や特定遺伝型では出血リスクに留意する。\n【誤答】『低下を完全停止し症状回復』は誇大で、効果はあくまで進行の緩和にとどまるため、この文脈で不適切。",
    source: { title: "Lecanemab in Early Alzheimer's Disease (CLARITY-AD, NEJM 2023)", url: "https://www.nejm.org/doi/full/10.1056/NEJMoa2212948" },
    tags: ["認知症", "アルツハイマー病", "抗アミロイド抗体", "複数選択"]
  },
  {
    id: "cl-uti-gepo-01",
    category: "clinical",
    difficulty: 2,
    added: "2026-07-23",
    question: "25歳女性、排尿時痛・頻尿の急性単純性膀胱炎。地域のST合剤耐性率が高く、過去にニトロフラントインで強い悪心があった。2024年の第3相EAGLE-2/3で有効性が示された新規経口抗菌薬はどれか。",
    options: ["ホスホマイシン単回経口", "ニトロフラントイン5日間", "ST合剤(トリメトプリム・スルファメトキサゾール)3日間", "ゲポチダシン(新規トリアザアセナフチレン系の経口抗菌薬)"],
    correct: 3,
    explanation: "【要点】局所のST合剤耐性が高くニトロフラントイン不耐がある本例では、2024年に第3相EAGLE-2/3で有効性が示された新規経口抗菌薬ゲポチダシンが選択肢となる。\n【背景/エビデンス】ゲポチダシンは細菌のトポイソメラーゼII/IVを新規機序で阻害するトリアザアセナフチレン系。EAGLE-2/3(計約3,100例)でニトロフラントインに非劣性、EAGLE-3では優越性を示した。主な有害事象は軽〜中等度の下痢だった。\n【臨床応用/注意】耐性菌が問題となる状況で経口治療の幅を広げるが、地域の感受性・薬剤相互作用・コストを踏まえ適応を個別化する。\n【誤答】ホスホマイシン・ニトロフラントイン・ST合剤も単純性膀胱炎の妥当な選択肢だが、設問が問う『EAGLEで検討された新規薬』には当たらず、この文脈で最適でない。",
    source: { title: "Oral Gepotidacin versus Nitrofurantoin in Uncomplicated Urinary Tract Infection (EAGLE-2 and EAGLE-3, Lancet 2024)", url: "https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(23)02196-7/abstract" },
    tags: ["感染症", "尿路感染症", "ゲポチダシン", "抗菌薬"]
  },
  {
    id: "rv-vms-nk-01",
    category: "review",
    difficulty: 1,
    added: "2026-07-23",
    question: "閉経に伴う中等症〜重症の血管運動症状(ホットフラッシュ)に用いる非ホルモン薬フェゾリネタント・エリンザネタントの作用機序として正しいものはどれか。",
    options: ["選択的エストロゲン受容体モジュレーター(SERM)である", "ニューロキニン(NK3ないしNK1/NK3)受容体拮抗薬で、視床下部の体温調節を修飾する", "選択的セロトニン再取り込み阻害薬(SSRI)である", "低用量の経皮エストロゲン製剤である"],
    correct: 1,
    explanation: "【要点】フェゾリネタントとエリンザネタントは、閉経期の中等症〜重症血管運動症状に用いる非ホルモン性のニューロキニン受容体拮抗薬で、視床下部KNDyニューロンを介した体温調節の乱れを是正する。\n【背景/エビデンス】フェゾリネタントはNK3拮抗薬、エリンザネタントはNK1/NK3デュアル拮抗薬。第3相(SKYLIGHT、OASIS 1/2など)でホットフラッシュの頻度・重症度を有意に低下させ、エリンザネタントは睡眠の改善も示した。\n【臨床応用/注意】ホルモン療法が禁忌・忌避の女性に有用な選択肢。フェゾリネタントでは肝機能のモニタリングが推奨され、頭痛等の有害事象にも留意する。\n【誤答】SERM・SSRI・経皮エストロゲンはいずれも実在する更年期関連の治療だが、両薬の分類としては誤りである。",
    source: { title: "Elinzanetant for Vasomotor Symptoms Associated With Menopause: OASIS 1 and 2 Randomized Clinical Trials (JAMA 2024)", url: "https://pubmed.ncbi.nlm.nih.gov/39172446/" },
    tags: ["更年期", "血管運動症状", "ニューロキニン受容体拮抗薬", "非ホルモン療法"]
  },
  {
    id: "gl-masld-fib4-01",
    category: "guideline",
    difficulty: 2,
    added: "2026-07-23",
    question: "2025年ADA Standards of Careにおける、2型糖尿病・前糖尿病患者のMASLD/MASH関連肝線維化スクリーニングの初期評価法として推奨されるものはどれか。",
    options: ["肝酵素が正常でも、FIB-4(年齢・AST・ALT・血小板から算出)でリスクを層別化する", "全例に直ちに肝生検を行う", "腹部造影CTを一次スクリーニングとする", "ALTが正常であれば肝疾患リスクは否定でき、追加評価は不要とする"],
    correct: 0,
    explanation: "【要点】2025年ADA Standards of Careは、2型糖尿病・前糖尿病(特に肥満・心代謝リスク併存)の患者に対し、肝酵素が正常でもFIB-4でMASH関連の進行性線維化リスクを評価するよう推奨する。\n【背景/エビデンス】FIB-4は年齢・AST・ALT・血小板から算出する簡便な指標。1.3超では追加のリスク層別化(肝硬度測定やELF)を行い、高リスク例は消化器・肝臓専門医へ紹介する。NAFLD/NASHはMASLD/MASHへ用語が更新された。\n【臨床応用/注意】ALT正常でも進行例が存在するため酵素値のみで否定せず、まずFIB-4で拾い上げる段階的アプローチが要点。\n【誤答】全例即生検・造影CTの一次スクリーニング・ALT正常で評価不要は、いずれも現行の推奨と異なる。",
    source: { title: "Summary of Revisions: Standards of Care in Diabetes—2025 (Diabetes Care)", url: "https://diabetesjournals.org/care/article/48/Supplement_1/S6/157564/Summary-of-Revisions-Standards-of-Care-in-Diabetes" },
    tags: ["糖尿病", "MASLD", "FIB-4", "肝線維化"]
  }
];

if (typeof module !== "undefined") { module.exports = QUESTIONS; }
